pagarme/pilot

assets/icons/applications-accessories.svg
assets/icons/applications-accessories_backup.svg

According to #1 we needed to create a directory structure. This commit
adds the structure discussed there.

architecture: add directory structure for assets

---

.gitignore

Ignore common files generated by operating systems.

Ignorar arquivos criados pelos sistemas operacionais 

---

.travis.yml
webapp/.storybook/config.js
webapp/package.json
webapp/yarn.lock

This adds Percy integration for visual regression analysis.

Add percy integration

---

webapp/src/styles/colors/dark.css

The secondary green colors were all the same

Fix secondary green colors

---

README.md

readme: add missing link to Pull Request

---

webapp/src/components/Alert/index.js
webapp/stories/Alert/index.js

Refactors Alert to keep up with the new naming scheme proposed in PR #212
Changes font family to UniSans

Rename alert theme and base props

---

webapp/config/webpack.config.storybook.js

Isso ajuda a gente a ver o nome das classes +- no DevTools durante desenvolvimento.

storybook: add cssmodules localIdentName option

---

webapp/src/components/Card/index.js
webapp/src/components/Card/properties.css
webapp/src/styles/index.css
webapp/src/styles/spacing.css

This adds standard spacing custom properties and applies on Card component.

Add spacing custom properties

---

webapp/src/components/Card/properties.css

Fix styles in cards so it includes its dependencies

cards: fix spacing

---

webapp/src/components/Alert/style.css
webapp/src/components/Card/style.css
webapp/src/components/CheckboxGroup/style.css
webapp/src/components/CircularProgress/style.css
webapp/src/components/LinearProgress/style.css
webapp/src/components/Switch/properties.css
webapp/src/components/Switch/style.css
webapp/src/components/TabBar/style.css

Isso deve adicionar o reset em todo o projeto e storybook.

style: add box-sizing reset

---

webapp/package.json
webapp/src/components/DateRange/DateRange.test.js
webapp/src/components/DateRange/__mocks__/shortid.js
webapp/src/components/DateRange/index.js
webapp/src/components/DateRange/properties.css
webapp/src/components/DateRange/style.css
webapp/stories/DateRange/index.js
webapp/stories/__snapshots__/storyshots.test.js.snap
webapp/stories/index.js
webapp/yarn.lock

A parte do date-picker estamos deixando para mais tarde

Add date range

---

webapp/src/components/SearchField/SearchField.test.js
webapp/src/components/SearchField/index.js
webapp/src/components/SearchField/properties.css
webapp/src/components/SearchField/style.css
webapp/stories/Toolbox/SearchField.js
webapp/stories/Toolbox/index.js
webapp/stories/__snapshots__/storyshots.test.js.snap
webapp/stories/index.js

search-field: add implementation

---

webapp/src/components/Card/Card.test.js
webapp/src/components/Card/index.js
webapp/src/components/Card/properties.css
webapp/src/components/Card/style.css
webapp/stories/Card/index.js
webapp/stories/__snapshots__/storyshots.test.js.snap

CardTitle: add property onClick

---

webapp/src/components/Toolbar/DateRange/index.js
webapp/stories/Toolbar/DateRange.js
webapp/stories/__snapshots__/storyshots.test.js.snap

This fixes an awkward situation where visually the DateRange component
changed state but doesn't reflected on real state or props.

Fix DateRange not changing checked state

---

webapp/src/components/Button/index.js
webapp/stories/__snapshots__/storyshots.test.js.snap

This property allows buttons to behave as a submit button inside form elements.
```jsx
<form action="/" method="post">
<Button type="submit">Submit Form</Button>
</form>
```
Buttons with no `type` will have a `type="button"` by default!
:)

buttons: add type property

---

webapp/src/components/Card/CardSection.js
webapp/src/components/Card/CardSection.style.css
webapp/src/components/Card/CardSection.test.js
webapp/src/components/Card/index.js
webapp/src/components/Card/properties.css
webapp/stories/Card/index.js
webapp/stories/__snapshots__/storyshots.test.js.snap

card-section: add implementation

---

webapp/src/index.js
webapp/src/style.css
webapp/src/styles/index.css

This simplifies a bit the styles entrypoint, moving `src/style.css` content to `src/styles/index.css`.

Refactor styles entrypoint to styles/index.css

---

webapp/src/components/Card/CardSection.js
webapp/src/components/Card/CardSection.style.css
webapp/src/components/Card/properties.css
webapp/stories/Card/index.js
webapp/stories/__snapshots__/storyshots.test.js.snap

card-section: add subtitle

---

webapp/src/components/Button/index.js
webapp/src/components/Button/properties.css
webapp/src/components/Button/style.css
webapp/stories/Button/index.js
webapp/stories/__snapshots__/storyshots.test.js.snap

This PR only add the new sizes, the last button spec lists the following sizes:
- extra-small
- small
- default
- large
Check it out here https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/59f73bdba1e6b1a37f5bc5a3

buttons: refactor size property

---

webapp/.storybook/config.js
webapp/package.json
webapp/yarn.lock

The timestemp is 2017-09-30T23:50:00.000Z it is the day
@greenboxal left Brazil.
It must not break the Percy build.

storybook: add mockdate module

---

webapp/package.json
webapp/src/components/Alert/index.js
webapp/src/components/Button/index.js
webapp/src/components/Checkbox/index.js
webapp/src/components/CircularProgress/style.css
webapp/src/components/ContextSwitch/index.js
webapp/src/components/DateSelector/index.js
webapp/src/components/Dropdown/properties.css
webapp/src/components/Dropdown/style.css
webapp/src/components/Switch/index.js
webapp/src/components/TabBar/TabItem.js
webapp/src/components/TabBar/TabItem.style.css
webapp/src/components/TabBar/properties.css
webapp/src/components/TabBar/style.css
webapp/src/components/Toolbar/DateInput/classNames.js
webapp/src/components/Toolbar/DateInput/classNames.style.css
webapp/src/components/Toolbar/DateInput/index.js
webapp/src/components/Toolbar/DateInput/style.css
webapp/src/components/Toolbar/DateRange/index.js
webapp/src/components/Toolbar/SearchField/index.js
webapp/src/components/Toolbar/index.js
webapp/stories/Button/index.js
webapp/stories/Colors/style.css
webapp/stories/Grid/CardSample.js
webapp/stories/Grid/CardSample.style.css
webapp/stories/Grid/style.css
webapp/stories/Progress/index.js
webapp/stories/__snapshots__/storyshots.test.js.snap
webapp/yarn.lock

This adds a linter for catching unused and undefined classes in CSS files.
Also fixes all errors found in all components and stories.

Add linter for unused & undefined styles, fixing them

---

webapp/package.json
webapp/src/components/Modal/Modal.test.js
webapp/src/components/Modal/index.js
webapp/src/components/Modal/properties.css
webapp/src/components/Modal/style.css
webapp/stories/Modal/index.js
webapp/stories/Modal/style.css
webapp/stories/__snapshots__/storyshots.test.js.snap
webapp/stories/index.js
webapp/stories/storyshots.test.js
webapp/yarn.lock

At this branch, I tested two libraries `react-toolbox` and `react-modal` I found react-modal to work much better than react-toolbox but I need your review on it.
closes #294

Add modal component

---

webapp/src/components/Button/colors.css
webapp/src/components/Button/properties.css
webapp/src/components/Button/style.css
webapp/src/styles/colors.css
webapp/stories/Button/index.js
webapp/stories/__snapshots__/storyshots.test.js.snap

Adjust and add states to buttons
Remove gradient silver, this variation does not exist
Fix gradient angle
Complete examples
closes #284

Button state

---

webapp/src/components/Toolbar/Pagination/Pagination.test.js
webapp/src/components/Toolbar/Pagination/index.js
webapp/src/components/Toolbar/Pagination/properties.css
webapp/src/components/Toolbar/Pagination/style.css
webapp/src/components/Toolbar/properties.css
webapp/stories/Toolbar/Pagination.js
webapp/stories/Toolbar/index.js
webapp/stories/__snapshots__/storyshots.test.js.snap

pagination: add basic component

---

.gitattributes

Este PR é um cherry-pick do PR #323 que é uma melhoria do PR #307 que é uma correção da issue #295 
Este Pull Requests:
- closes #323 Obrigado @andreolvr
- closes #307 obrigado @gpgabrielpaiva
- closes #295

core: add .gitattributes file to fix linebreaks

---

webapp/.editorconfig

it uses some basic configurations for all files like indenting rules and
newline patterns
more rules can be set if needed
closes #330

chore: add .editorconfig file

---

webapp/src/components/Modal/properties.css
webapp/src/components/Modal/style.css

modal: fix icon margin

---

webapp/src/styles/colors/light.css

Fix low relevance colors gradients

Fix button colors properties

---

webapp/.editorconfig

Adicionei duas regras, uma para garantir que todos os arquivos serão UTF-8 e outra para remover os espaços em branco desnecessários no fim das linhas.

chore: update .editorconfig add rules

---

webapp/src/components/Input/Input.js

If one sets onBlur or/and onFocus, it will be executed after blur/focus
of the Component

input: fix blur/focus

---

.github/ISSUE_TEMPLATE.md

chore: add issue template

---

.circleci/config.yaml

Add basic circle CI configuration to run build, lint and tests in future commits

Add circle CI config

---

.eslintrc
.stylelintrc
package.json
packages/pilot/.storybook/.eslintrc
packages/pilot/.storybook/addons.js
packages/pilot/.storybook/config.js
packages/pilot/.storybook/preview-head.html
packages/pilot/.storybook/themeDecorator.js
packages/pilot/.storybook/webpack.config.js
packages/pilot/package.json
packages/pilot/src/containers/Account/Login/index.js
packages/pilot/src/containers/Account/PasswordRecovery/Confirmation.js
packages/pilot/src/containers/Account/PasswordRecovery/Form.js
packages/pilot/src/containers/Account/RegisteredPresentation.js
packages/pilot/src/containers/Account/SignUp/Confirmation.js
packages/pilot/src/containers/Account/SignUp/Form.js
packages/pilot/src/containers/Account/SignUp/InvalidEmailError.js
packages/pilot/src/containers/Account/SignUp/index.js
packages/pilot/src/containers/Account/UnregisteredPresentation.js
packages/pilot/src/containers/Account/index.js
packages/pilot/src/pages/Account/SignUp/index.js
packages/pilot/src/pages/Account/index.js
packages/pilot/stories/.eslintrc
packages/pilot/stories/Landing/index.js
packages/pilot/yarn.lock
yarn.lock

This adds Storybook, Jest HTML snapshot testing and Percy integration.

Add Storybook with Storyshots and Percy

---

packages/pilot/package.json
packages/pilot/src/App.js
packages/pilot/src/DevTools.js
packages/pilot/src/configureStore/development.js
packages/pilot/src/configureStore/index.js
packages/pilot/src/configureStore/production.js
yarn.lock

chore: add redux-dev-tools

---

README.md

Esse PR adiciona o README devolta, depois da migração do monorepo.

Adiciona o README de volta

---

packages/pilot/src/components/TransactionHead/index.js
packages/pilot/src/components/TransactionHead/style.css
packages/pilot/stories/components/TransactionHead/index.js
packages/pilot/stories/components/index.js

transaction-head: add component

---

packages/pilot/src/components/TransactionDetailsCard/index.js
packages/pilot/src/components/TransactionDetailsCard/style.css
packages/pilot/stories/components/TransactionDetailsCard/index.js
packages/pilot/stories/components/index.js

transactions: add details card component

---

packages/pilot/src/components/CustomerCard/index.js
packages/pilot/src/components/CustomerCard/style.css
packages/pilot/stories/components/CustomerCard/index.js
packages/pilot/stories/components/index.js

customer: add card component

---

packages/pilot/src/components/TotalDisplay/index.js
packages/pilot/src/components/TotalDisplay/style.css
packages/pilot/stories/components/TotalDisplay/index.js
packages/pilot/stories/components/index.js

total-display: add component

---

packages/pilot/src/pages/LoggedArea/Sidebar.js
packages/pilot/src/pages/LoggedArea/index.js

Replace `Object.values` with `R.values`
close #446

logged-area: remove Object.values

---

packages/pilot/src/containers/Sidebar.js

This pr fixed the sidebar logic that verifies whether the sidebardlink is active or not.

sidebar: fix sidebar active status check

---

packages/cockpit/src/index.js
packages/cockpit/src/proxy.js
packages/cockpit/src/proxy.test.js
packages/pilot/src/pages/Account/actions/epic.js
packages/pilot/src/pages/Transactions/Details/Details.js
packages/pilot/src/pages/Transactions/Search/Search.js

cockpit: add proxy fallback

---

packages/pilot/src/components/TotalDisplay/index.js
packages/pilot/src/components/TotalDisplay/style.css
packages/pilot/src/containers/TransactionDetails/index.js
packages/pilot/src/containers/TransactionDetails/style.css

- Remove `Card` and `CardContent` from `TotalDisplay`
- Add `Card` and `CardContent` in `TransactionsDetails`

total-display: remove card content from component

---

.circleci/config.yml
packages/cockpit/src/transactions/details/mocks/expectedResultBoleto.json
packages/cockpit/src/transactions/details/mocks/expectedResultMock.json
packages/cockpit/src/transactions/details/result.js
packages/pilot/public/index.html
packages/pilot/public/locales/pt/transactions.json
packages/pilot/src/containers/TransactionDetails/index.js
packages/pilot/src/containers/TransactionsList/index.js
packages/pilot/src/environment.js
packages/pilot/src/models/transactionFilterOptions/transactionStatus.js
packages/pilot/src/models/transactionOperationTypes.js
packages/pilot/src/pages/Account/actions/epic.js

Demorou pra sair mas tamos aí!!

Release Versão 0.1.3

---

.circleci/config.yml

fix sync command on aws s3, the build is broken until this feature is merged

fix: change order in command aws s3 sync

---

packages/pilot/src/components/CopyButton/index.js
packages/pilot/stories/components/CopyButton/index.js

Refactor copy button interface to be a wrapper for Button component

Refactor copy button interface

---

packages/pilot/src/components/DataDisplay/index.js
packages/pilot/src/components/DataDisplay/style.css
packages/pilot/src/components/TotalDisplay/index.js
packages/pilot/src/components/TotalDisplay/style.css
packages/pilot/stories/components/DataDisplay/index.js
packages/pilot/stories/components/index.js

Componente criado com base no TotalDisplay (que agora eh feito em cima do CardDisplay) para que tivessemos um componente igual o TotalDisplay mas que nao aceitasse apenas numeros

Add DataDisplay component

---

packages/pilot/src/models/statusLegends.js
packages/pilot/src/models/transactionFilterOptions/transactionStatus.js

Add support to new transaction status `pending_review`

transaction: add pending_review status

---

packages/cockpit/src/transactions/details/mocks/expectedResultMock.json
packages/cockpit/src/transactions/details/mocks/fromRequests.json
packages/cockpit/src/transactions/details/result.js
packages/pilot/src/models/transactionOperationTypes.js

Refactor cockpit and pilot to support new statuses and operation types and also ignore unused statuses or types

Refactor operations

---

.circleci/config.yml

we now send message in case of hold button is activated

chore: add slack webhook in build

---

packages/pilot/src/components/DataDisplay/style.css
packages/pilot/src/components/DetailsHead/index.js
packages/pilot/src/components/DetailsHead/style.css
packages/pilot/src/components/TotalDisplay/style.css
packages/pilot/src/containers/TransactionDetails/index.js

This refactors leaking margins that happened after removing Card from
some component root. This PR fixes them by moving CardContent outside
and also fixes other leaking marging happening on data display.

Refactor various leaking margins on shared components

---

packages/pilot/src/components/RecipientCard/index.js
packages/pilot/src/components/RecipientCard/style.css

The `RecipientCard` component breaks after the update in `Grid` component, this PR makes some changes to fix this.
- Remove `Grid` from card.
- Update styles.

transaction-details: fix recipient-card component

---

packages/pilot/src/containers/Withdraw/Result/style.css

fix error feedback image alignment

withdraw: fix error alignment

---

packages/pilot/public/locales/pt/translations.json
packages/pilot/src/containers/ManualReview/Result/index.js
packages/pilot/src/containers/TransactionsList/index.js
packages/pilot/src/pages/Transactions/Search/Search.js

corrige bugs reportados no fluxo de analise manual de antifraude (#738, #758)

Release v0.2.1

---

packages/pilot/package.json
yarn.lock

Update Emblematic Icons version `0.3.1` ~> `0.4.0`

package: update emblematic icons

---

packages/pilot/src/containers/Sidebar.js

- Add redirect button to the old Dashboard

sidebar: add button to the old dashboard

---

CONTRIBUTING.md
README.md

This adds an extended release flow explanation to main README.md. This
should help on newcomers and developer onboarding experience and expectatives.

Add extended release explanation

---

packages/pilot/src/components/ConfigurationCardForm/index.js
packages/pilot/stories/components/ConfigurationCardForm/index.js
packages/pilot/stories/components/ConfigurationCardForm/style.css
packages/pilot/stories/components/index.js

Este PR adiciona o componete ConfigurationCardForm, com ele nós podemos
simplesmente usar o mesmo card alterando apenas algumas props,
facilitando o desenvolvimento.
resolve #784

configurations: add configuration card form

---

packages/pilot/src/components/TotalDisplay/index.js

Fix warnigs components

---

packages/pilot/public/locales/pt/translations.json
packages/pilot/src/components/ConfigurationCardForm/index.js
packages/pilot/src/containers/Settings/Boleto/Form/index.js
packages/pilot/stories/components/ConfigurationCardForm/index.js
packages/pilot/stories/containers/Settings/Boleto/Form.js
packages/pilot/stories/containers/index.js

Cria o container do formulário de edição do Boleto.
Resolve a issue #786.

settings: add boleto form container

---

packages/pilot/src/containers/Settings/BankAccount/Add/index.js
packages/pilot/src/containers/Settings/BankAccount/Add/style.css
packages/pilot/stories/containers/Settings/BankAccount/Add/index.js
packages/pilot/stories/containers/index.js

Para testar esse branch é necessário usar ele linkado com o branch `master` do projeto https://github.com/derekstavis/react-vanilla-form pois apesar de o PR de bugfix ja ter sido mergeado ainda não foi publicada uma nova versão no npm 
resolves #838

bank-account: add bank account form

---

packages/pilot/src/components/BalanceSummary/index.js
packages/pilot/src/components/TotalDisplay/index.js
packages/pilot/src/containers/Anticipation/Confirmation/index.js
packages/pilot/src/containers/Anticipation/Form/index.js
packages/pilot/src/containers/Anticipation/Result/index.js
packages/pilot/src/containers/TransactionDetails/index.js
packages/pilot/src/containers/Withdraw/Confirmation/index.js
packages/pilot/src/containers/Withdraw/Form/index.js
packages/pilot/src/containers/Withdraw/Result/index.js
packages/pilot/src/pages/Transactions/Details/Details.js
packages/pilot/stories/components/Summary/index.js
packages/pilot/stories/components/TotalDisplay/index.js
packages/pilot/stories/pages/TransactionDetails/index.js

Total Display: Refactor unit values

---

packages/pilot/public/locales/pt/translations.json
packages/pilot/src/containers/Settings/BankAccount/Add/index.js
packages/pilot/src/containers/Settings/BankAccount/Add/style.css
packages/pilot/src/containers/Settings/BankAccount/Selector/index.js
packages/pilot/src/containers/Settings/BankAccount/index.js
packages/pilot/stories/containers/Settings/BankAccount/index.js
packages/pilot/stories/containers/index.js

bank-accounts-settings: add main container

---

packages/pilot/src/containers/AddRecipient/ConfigurationStep/index.js
packages/pilot/src/containers/AddRecipient/ConfigurationStep/style.css
packages/pilot/src/pages/LoggedArea/routes.js
packages/pilot/stories/containers/AddRecipient/ConfigurationsStep/index.js
packages/pilot/stories/containers/index.js

Baseado no [PR](https://github.com/pagarme/pilot/pull/865) para corrigir um erro de 'Rebase' que ocasionou no Drop do 'commit'

configuration-step: add component

---

packages/pilot/src/pages/Anticipation/index.js

Atualmente na página de antecipação buscamos todas antecipações e então filtramos apenas as que tem o status `building`, esse PR tira a necessidade de filtrar no client uma vez que agora a API suporta o filtro por status.

anticipations: remove client side filter by status building

---

packages/pilot/stories/pages/Landing/index.js

Faltou passar a base nos stories e está trazendo um erro no console.

account: add base to login stories

---

packages/pilot/public/locales/pt/translations.json
packages/pilot/src/containers/AddRecipient/BankAccountStep/AddAccount/AddAccountContent.js
packages/pilot/src/containers/AddRecipient/BankAccountStep/AddAccount/index.js
packages/pilot/src/containers/AddRecipient/BankAccountStep/SelectAccount/SelectAccountContent.js
packages/pilot/src/containers/AddRecipient/BankAccountStep/SelectAccount/index.js
packages/pilot/src/containers/AddRecipient/ConfigurationStep/Anticipation/index.js
packages/pilot/src/containers/AddRecipient/ConfigurationStep/Transfer/index.js
packages/pilot/src/containers/AddRecipient/ConfigurationStep/index.js
packages/pilot/src/containers/RecipientDetails/Config/AnticipationContent/index.js
packages/pilot/src/containers/RecipientDetails/Config/BankAccount32.svg
packages/pilot/src/containers/RecipientDetails/Config/BankAccountContent/index.js
packages/pilot/src/containers/RecipientDetails/Config/RecipientItem/index.js
packages/pilot/src/containers/RecipientDetails/Config/TransferContent/index.js
packages/pilot/src/containers/RecipientDetails/Config/contentIds.js
packages/pilot/src/containers/RecipientDetails/Config/index.js
packages/pilot/src/containers/RecipientDetails/Config/style.css
packages/pilot/stories/containers/RecipientDetails/Config/index.js
packages/pilot/stories/containers/index.js

Aba de Configurações de Detalhes do Recebedor. Este PR aproveita Components dos passos de Configurações e Conta Bancária. 
- [Issue 263](https://github.com/pagarme/caesar/issues/263)
-------------------------------
-------------------------------
[Zeplin](https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5b647212309bd5e47bb31152)

recipient-config: add container

---

packages/pilot/public/locales/pt/translations.json
packages/pilot/src/containers/SelfRegister/CompanyData/index.js
packages/pilot/src/containers/SelfRegister/CreateAccount/index.js
packages/pilot/src/containers/SelfRegister/PartnerAddress/index.js
packages/pilot/src/containers/SelfRegister/PartnerData/index.js
packages/pilot/src/containers/SelfRegister/TypeCNPJ/index.js
packages/pilot/src/containers/Settings/Company/TeamInfoTab/TeamManagement/AddNewUserModal.js
packages/pilot/src/validation/cep.js
packages/pilot/src/validation/cnpj.js
packages/pilot/src/validation/cpf.js
packages/pilot/src/validation/date.js
packages/pilot/src/validation/email.js
packages/pilot/src/validation/legalAge.js
packages/pilot/src/validation/phone.js

Este PR adiciona validações necessárias aos campos do formulário de autocredenciamento.
Adiciona validação de:
[insira o screenshot aqui]
[insira o screenshot aqui]
**Novos scripts**:
- `script` : detalhes do script
**Novas dependências**:
- `dependency` : detalhes da dependência
**Novas dependências de desenvolvedor**:
- `dependency` : detalhes da dependência

pilot: add self register validations

---

packages/pilot/public/locales/pt/translations.json
packages/pilot/src/containers/SelfRegister/PartnerData/index.js

Este PR remove o campo de email do sócio, pois não precisamos desta informação.

pilot: remove self register partner email

---

packages/pilot/package.json
packages/pilot/src/components/ClientForm/index.js
packages/pilot/src/components/ClientForm/style.css
packages/pilot/src/validation/cnpj.js
packages/pilot/src/validation/cpf.js
packages/pilot/src/validation/email.js
packages/pilot/src/validation/phone.js
packages/pilot/stories/components/ClientForm/index.js
packages/pilot/stories/components/index.js
yarn.lock

Este PR adiciona o formulário de adicionar um cliente na página de adicionar transação.
**Novas dependências**:
- [validator](https://www.npmjs.com/package/validator) : lib de validações.
**Como testar:**
- Precisa linkar com a branch master do `former-kit-skin-pagarme`
- faça checkout pra esta branch: `git checkout add/transaction-client-form`
- rode o storybook: `yarn storybook`
**OBS:**
Os commit de **validations** podem ser dropados eventualmente porque já existem em PR's de outras features.

add-transaction: add clientForm component

---

packages/cockpit/src/company/register/index.js

Adiciona campo `primary_phone` como campo que é enviado a

self-register: add primary_phone field

---

packages/cockpit/src/company/register/index.js

Implementa um fix para formatação de números de telefone

company-register: format phone number

---

yarn.lock

Fix the `event-stream` and `flatmap-stream` dependency which had a major security issue as related in the following isuue:
https://github.com/dominictarr/event-stream/issues/116

Fix event-stream and flatmap-stream dependencies

---

packages/pilot/package.json
packages/pilot/public/locales/pt/translations.json
packages/pilot/src/components/PasswordInput/index.js
packages/pilot/src/components/PasswordInput/style.css
packages/pilot/stories/components/PasswordInput/index.js
packages/pilot/stories/components/index.js
yarn.lock

Este PR adiciona um componente de `Input` + `Popover` para validação de força de senha.
**Novas dependências**:
- https://github.com/pagarme/p4g4rm3
**Como rodar:**
- Rode o comando `yarn` para instalar novas deps.
- Linkar com [forker-kit](https://github.com/pagarme/former-kit) (lembrando que a branch master precisa estar atualizada).
- Rode o storybook `yarn storybook`.

components: add input with password strength as component

---

packages/pilot/package.json
packages/pilot/public/locales/pt/translations.json
packages/pilot/src/containers/Account/LoginForm/index.js
packages/pilot/src/containers/Account/PasswordRecovery/Form.js
packages/pilot/src/containers/Account/SignUp/Form.js
packages/pilot/src/containers/Account/style.css
packages/pilot/src/pages/Account/Login/index.js
packages/pilot/src/pages/Account/PasswordRecovery/buildResetParamErrors.js
packages/pilot/src/pages/Account/PasswordRecovery/index.js
packages/pilot/src/validation/email.js
yarn.lock

Este PR adiciona o request para a rota `/users/reset_password` enviando o e-mail digitado.
issue #1045

Password Reset

---

packages/pilot/src/pages/Balance/Balance.js

Para validar esse pull request você deve acessar o link da release candidate e validar os pontos descritos abaixo
- ajusta a versão da exportação de extrato (csv/xlsx)
- balance: update export version #1153
relacionado a #1154

release v0.10.2

---

packages/pilot/package.json
packages/pilot/public/locales/pt/translations.json
packages/pilot/src/containers/Settings/Company/GeneralInfoTab/ApiKey/index.js
packages/pilot/src/containers/Settings/Company/GeneralInfoTab/Versions/index.js
packages/pilot/src/containers/Settings/Company/GeneralInfoTab/Versions/style.css
packages/pilot/src/containers/Settings/Company/GeneralInfoTab/index.js
packages/pilot/src/containers/Settings/Company/index.js
packages/pilot/src/pages/CompanySettings/index.js
yarn.lock

Para validar esse pull request acesse os links onde esta versão foi publicada
Essa release tem como objetivo principal adicionar na tela de configurações a opção do usuário poder alterar a versão da API.
- settings: add possibility to change api version #1260
- Implementar na página de configuração apenas para usuários "admin" e com permissão de "escrita".

release 0.15.0 - 18/06/2019

---

CONTRIBUTING.md

Remove o gênero de uma frase no arquivo `CONTRIBUTING.md`.
Cópia de https://github.com/pagarme/pilot/pull/1326

chore: remove gender from contributing file

---

.github/ISSUE_TEMPLATE/issue-template.md
.github/ISSUE_TEMPLATE/release-issue-template.md

adiciona novos templates de issue

chore: update issue templates

---

packages/pilot/public/index.html

Estamos com problema de cors no https://unpkg.com o que faz a Pilot não abrir em produção.

react: change cdn

---

packages/cockpit/src/balance/mocks/operation/expected.json
packages/cockpit/src/balance/mocks/operations/expected.json
packages/cockpit/src/balance/mocks/payables/expected.json
packages/cockpit/src/balance/operations/operations.js
packages/cockpit/src/balance/operations/operations.test.js
packages/cockpit/src/balance/operations/shared.js
packages/pilot/src/components/Operations/operationsTableColumns.js

Esta versão corrige um bug relacionado a exibição de taxas de gateway na tela de extrato
- Extrato - Adicionar suporte à cobranças de gateway #1510
- Extrato - Adiciona suporte à cobranças de gateway #1511
issues relacionadas #1518

Release v0.21.4

---

packages/pilot/src/components/DetailsHead/style.css
packages/pilot/src/components/MetricChart/charts/RadialChart/style.css
packages/pilot/src/components/MetricList/style.css
packages/pilot/src/containers/Home/Header.js
packages/pilot/src/containers/Home/style.css

Após levantamento feito na issue #1468, verificamos a necessidade de ajustes visuais, dado as diferenças entre o que está codado e os valores estabelecidos em layout.

Fix details of style

---

packages/pilot/src/vendor/googleTagManager.js

Esta release contém uma correção no Google Analytics para evitar a duplicidade na identificação dos usuários.
- google-analytics: set userId #1533

Release v0.21.6

---

packages/pilot/src/components/WelcomeMessage/index.js
packages/pilot/src/components/WelcomeMessage/styles.css
packages/pilot/src/containers/EmptyState/AccessDocs/index.js
packages/pilot/src/containers/EmptyState/AccessDocs/styles.css
packages/pilot/src/containers/EmptyState/AccessKeys/index.js
packages/pilot/src/containers/EmptyState/AccessKeys/styles.css

PR para corrigir problemas encontrados na release que adiciona o EmptyState

Onboarding: Adicionar EmptyState - Correções

---

packages/pilot/src/containers/PaymentLinks/NewLinksCard/index.js
packages/pilot/src/containers/PaymentLinks/NewLinksCard/style.css
packages/pilot/stories/components/NewLinksCard/index.js
packages/pilot/stories/components/index.js

Esse PR adiciona um card para criação de novos links de pagamento que será usado futuramente na tela /payment-links

payment-links: add NewLinksCard

---

packages/pilot/public/locales/pt/translations.json
packages/pilot/src/containers/PaymentLinks/PaymentLinkAdd/FirstStep.js
packages/pilot/src/containers/PaymentLinks/PaymentLinkAdd/style.css
packages/pilot/stories/containers/PaymentLinks/PaymentLinkAdd/index.js
packages/pilot/stories/containers/index.js

Este PR adiciona o primeiro step do modal da criação do link de pagamento.
Rodar o storybook :)

payment-links: add new link first step

---

packages/pilot/src/components/FeesDetails/index.js

Update credit card translation path.

fees-details: update credit card fees

---

packages/pilot/src/pages/Account/actions/epic.js

Ao fazer o refresh da página estamos desconectando o usuário. Isto acontece porque perdemos o acesso à capability `allow_dashboard_login`. Este PR ajusta a verificação para fazer um GET em /company e validarmos por agora pelo tipo da company, pois esta capability também não é retornada em `GET /company`.
1. Faça o login
2. Recarregue a página após conectado

Login - Refatora verificação de permissionamento

---

packages/pilot/src/pages/LoggedArea/Sidebar.js

Permite a visualizacao da pagina de links de pagamentos em Sandbox.

CRED-169 plinks: update visibility in sandbox

---

packages/cockpit/src/paymentLinks/transactions/index.js
packages/pilot/src/containers/PaymentLinks/List/PaymentLinkAdd/FirstStep/validators.js

Este card altera as mensagens que são exibidas na validação do link de pagamentos

CRED-172 plinks: update required messages

---

packages/pilot/package.json
packages/pilot/public/locales/pt/translations.json
packages/pilot/src/containers/Account/LoginForm/index.js
packages/pilot/src/containers/PaymentLinks/Details/Header/index.js
packages/pilot/src/containers/PaymentLinks/Details/Info/index.js
packages/pilot/src/containers/PaymentLinks/List/PaymentLinkAdd/FirstStep/validators.js
packages/pilot/src/pages/PaymentLinks/Details/Details.js
yarn.lock

Corrigi pequenos problemas que foram levantados dentro da Pagar.me após a liberação do teste em Sandbox.

CRED-175 Fix/payment links

---

packages/cockpit/src/paymentLinks/transactions/index.js
packages/pilot/src/containers/PaymentLinks/Details/TransactionsList/tableColumns.js

Aplica o transactionSpec na busca por transações realizadas pelo link de pagamentos.

CRED-180 plinks: refactor apply transactionSpec

---

.circleci/config.yml

Atualiza a key do recaptcha em sandbox.

chore: update recaptcha key on sandbox

---

packages/pilot/src/pages/LoggedArea/Sidebar.js
packages/pilot/src/pages/LoggedArea/index.js
packages/pilot/src/pages/LoggedArea/routes.js

Remove a trava de visibilidade da pagina de link de pagamentos que foi criada no commit https://github.com/pagarme/pilot/commit/21b29b098b9ccd55e27083b84d6a1a098b006e86.
_Esta issue será deployada após 16/07_

CRED-154 Remove a trava de visibilidade da pagina de link de pagamento

---

.circleci/config.yml
packages/pilot/.storybook/percyIntegration.js
packages/pilot/package.json
yarn.lock

Melhora o tempo de execução do build na Pilot.
[CRED-176](https://mundipagg.atlassian.net/browse/CRED-176)

CRED-176 Otimiza o CI da Pilot

---

packages/pilot/src/pages/Account/actions/epic.js

Notamos que o handling de erros de environment estava sendo disparado antes do carregamento da company. No último PR alteramos a lógica de renderização do `LoggedArea` (que tem o nosso ErrorBoundary) para retornar algo somente se `user` e `company` estiverem disponíveis. Consequentemente precisamos dar throw em um erro somenete após a renderização do nosso ErrorBoundary (que é garantido pela disponibilização de company).
1. Faça o login com uma company não ativa em modo live, rodando o projeto com:
```bash
env REACT_APP_API_ENVIRONMENT=live yarn start
```

EXP-202 - Corrige fluxo de verificação de environment

---

packages/pilot/src/containers/Account/LoginForm/index.js

Realiza o ajuste do handler do login para executar o recaptcha asincronamente, e, após este step, realizar a chamada do epico `requestLogin`.

login: refactor recaptcha handler

---

packages/pilot/public/locales/pt/translations.json
packages/pilot/src/containers/Withdraw/Result/index.js
packages/pilot/src/containers/Withdraw/Result/style.css

Este PR atualiza a mensagem de saque realizado na tela de saque de pagamento.

CRED-210 - Atualizar mensagem de saque realizado com sucesso

---

packages/pilot/src/pages/EmptyState/reducer.js
packages/pilot/src/pages/EmptyState/reducer.test.js
packages/pilot/src/validation/recentCreatedCompany.js

[CRED-241](https://mundipagg.atlassian.net/browse/CRED-241)

Company default onboarding

---

packages/pilot/public/locales/pt/translations.json
packages/pilot/src/components/FeesDetails/FeeDetails.test.js
packages/pilot/src/components/FeesDetails/__snapshots__/FeeDetails.test.js.snap
packages/pilot/src/containers/Onboarding/Welcome/Welcome.test.js
packages/pilot/src/containers/Onboarding/Welcome/__snapshots__/Welcome.test.js.snap
packages/pilot/src/containers/Onboarding/Welcome/index.js
packages/pilot/src/containers/Onboarding/Welcome/styles.css
packages/pilot/src/containers/Onboarding/index.js
packages/pilot/src/containers/Onboarding/styles.css
packages/pilot/src/pages/Onboarding/Onboarding.js
packages/pilot/stories/containers/Onboarding/index.js
packages/pilot/stories/containers/Onboarding/mocks.js
packages/pilot/stories/containers/index.js

Desenvolvemos uma nova tela inicial para a página de onboarding explicando um pouco mais sobre os benefícios do seu preenchimento.
[CRED-98](https://mundipagg.atlassian.net/browse/CRED-98)

onboarding: add welcome step

---

packages/pilot/package.json
packages/pilot/src/containers/Onboarding/Card/index.js
packages/pilot/src/containers/Onboarding/SegmentOptions/MacroSegments.js
packages/pilot/src/containers/Onboarding/SegmentOptions/MacroSegments.test.js
packages/pilot/src/containers/Onboarding/SegmentOptions/__snapshots__/MacroSegments.test.js.snap
packages/pilot/src/containers/Onboarding/SegmentOptions/index.js
packages/pilot/src/containers/Onboarding/SegmentOptions/styles.css
packages/pilot/src/containers/Onboarding/index.js
packages/pilot/stories/containers/Onboarding/index.js
packages/pilot/stories/containers/Onboarding/mocks.js
packages/pilot/stories/containers/index.js
yarn.lock

Este PR adiciona o componente de macrosegmentos do onboarding.

CRED-95 Adicionar a página de macrosegmentos do Onboarding

---

.circleci/config.yml
sonar-project.properties

CRED-185 Adiciona o Sonar

---

packages/cockpit/src/transactions/search/query.js
packages/cockpit/src/transactions/search/query.test.js

A visualização o relatório de transações apresenta valores que divergem do transacional. O cliente consultou os dias 17 e 18/08 e os valores não batem com o transacional dele. Quando ele filtrou somente o dia 17/08 o valor estava correto, e ao aumentar o período mudou.
<details><summary>query</summary>
<p>
```json
{
"type": "transaction",
"query": {"from":0,"size":15,"sort":[{"date_created":{"order":"desc"}}],"query":{"filtered":{"query":{"match_all":{}},"filter":{"and":[{"terms":{"status":["paid"]}},{"range":{"date_created":{"gte":"2020-08-17T03:00:00.000Z","lte":"2020-08-19T02:59:59.999Z"}}}]}}},"aggregations":{"total_amount":{"filter":{"term":{"status":"paid"}},"aggregations":{"amount":{"sum":{"field":"paid_amount"}}}},"total_cost":{"sum":{"field":"cost"}},"total_per_day":{"date_histogr …
```

cockpit: update transactions chart query

---

packages/pilot/public/locales/pt/translations.json

Corrige o typo [reportado pelo RC](https://pagarme.slack.com/archives/C3LUBHK5J/p1598875696033300).

CRED-273 chore: fix reported typo

---

packages/pilot/public/locales/pt/translations.json
packages/pilot/src/components/OnboardingBackground/styles.css
packages/pilot/src/containers/Onboarding/ProgressBar/index.js
packages/pilot/src/containers/Onboarding/SegmentOptions/MacroSegments.js
packages/pilot/src/containers/Onboarding/SegmentOptions/MacroSegments.test.js
packages/pilot/src/containers/Onboarding/SegmentOptions/SegmentOptions.test.js
packages/pilot/src/containers/Onboarding/SegmentOptions/Segments.js
packages/pilot/src/containers/Onboarding/SegmentOptions/Segments.test.js
packages/pilot/src/containers/Onboarding/SegmentOptions/__snapshots__/SegmentOptions.test.js.snap
packages/pilot/src/containers/Onboarding/SegmentOptions/__snapshots__/Segments.test.js.snap
packages/pilot/src/containers/Onboarding/SegmentOptions/index.js
packages/pilot/src/containers/Onboarding/SegmentOptions/styles.css
packages/pilot/src/pages/Onboarding/machine/settings.js
packages/pilot/stories/containers/Onboarding/index.js
packages/pilot/stories/containers/Onboarding/mocks.js
packages/pilot/stories/containers/index.js

Adiciona segmentos nas perguntas de onboarding

CRED-97 Adiciona segmentos nas perguntas de onboarding

---

packages/pilot/src/pages/Root.js

Este PR altera a regra de exibição do choose-dashboard para não exibir o componente para clientes do autocred e automaticamente enviar estes clientes para a nova dashboard.

CRED-165 Não mostrar tela de escolha de dashboard para clientes do autocred.

---

sonar-project.properties

Migração para o novo Sonar
- inclui nova propriedade para usar o sonarcloud
https://mundipagg.atlassian.net/browse/QA-91

QA-91: Sonar Migration

---

packages/pilot/src/pages/Account/actions/epic.js

Este PR adiciona um fix para quando o ES falha e a rota /transactions fica indisponivel.
Iremos no futuro remover a necessidade de verificar se o cliente já transacionou na rota /transactions e /payables.

CRED-315 chore: fix avoid errors on login

---

packages/pilot/src/components/FeesDetails/FeeDetails.test.js
packages/pilot/src/components/FeesDetails/index.js
packages/pilot/src/containers/EmptyState/Fees/index.js
packages/pilot/src/containers/EmptyState/index.js
packages/pilot/src/containers/Settings/Company/FeesTab/index.js
packages/pilot/src/containers/Settings/Company/index.js
packages/pilot/src/pages/CompanySettings/index.js
packages/pilot/src/pages/EmptyState/EmptyState.js
packages/pilot/stories/components/FeesDetails/index.js
packages/pilot/stories/components/index.js
packages/pilot/stories/containers/EmptyState/index.js
packages/pilot/stories/containers/index.js
yarn.lock

Exibe as taxas de Pix apenas quando a company tiver `pix` como `payment_method`.

fees: fix display pix only when enabled

---

packages/pilot/public/locales/pt/translations.json
packages/pilot/src/models/operationTypes.js

Adicionar descrição para transações pix na aba de extrato.

balance: add pix description

---

packages/pilot/src/pages/Home/Home.js
packages/pilot/stories/containers/Home/index.js
packages/pilot/stories/containers/Home/mocks.js
packages/pilot/stories/containers/index.js

Exibe o Pix na tela de Resumo apenas quando a company possui o Pix ativado.

home: add condition to display pix
