pagarme/pilot

- LICENSES.md
- README.md
Este PR adiciona a parte de licenciamento do projeto.
Acho importante ressaltar que o conteúdo de issues, pull-requests e também
todos os assets gráficos também precisam ser licenciados, para a seguranca
da companhia e também dos usuários do conteúdo.
Dado isso, selecionei o seguinte licenciamento:
* Base de código: **Apache 2.0 License**
* Gráficos, PRs e issues: **Creative Commons Atribution 4.0 International**
Gostaria da revisão dos senhores, e se posível da galera do jurídico também.
cc @filipedeschamps @jonathanlima
> Adiciona licenciamento do projeto

- .travis.yml
- webapp/config/stylelintFormatter.js
- webapp/config/webpack.config.dev.js
- webapp/config/webpack.config.prod.js
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/Button/style.css
- webapp/src/index.js
- webapp/src/style.css
- webapp/stories/__snapshots__/storyshots.test.js.snap
- webapp/stories/storyshots.test.js
- webapp/yarn.lock
Adiciona o pipeline de testes no Travis.
Acho que a unica coisa que falta é documentar os fluxos do snapshotting dos testes. Podemos ir melhorando progressivamente o README padrão do create-react-app.
Resolves: #179
> Add testing pipeline using Travis

- webapp/package.json
- webapp/yarn.lock
Bump stylelint pagarme-react config to 1.0.3.
Previous to this bump, this was considered an error:
.container > h2 {
some-rule: 0;
}
Now using type selector in 'child' and 'descendant' is allowed.
> Allow type selector in descendant and child

- webapp/stories/Card/style.css
The `:` create an error when css is processed
> cards: fix style

- webapp/.eslintrc
- webapp/package.json
create-react-app stores eslint configuration into `package.json`. When I
initially bootstraped the repo I've mistakenly crated an `.eslintrc` file.
This PR merges `.eslintrc` config into `package.json`.
> Move .eslintrc to package.json

- webapp/package.json
- webapp/yarn.lock
This fixes Percy not rendering fonts. This bug was fixed in a partnership with Percy developers, where they pushed a new version on NPM, which this PR bumps to.
Reference: percy/percy-storybook#8
> Fix percy font issue by bumping version

- webapp/package.json
Assim, o `yarn lint` localmente acusa alguns erros, porém com os mesmos erros ele passa no CI.
Então imaginei que isso poderia ajudar, porém vi que no CI ele está passando pelo lint, acusa os erros porém ele não quebra o CI com os erros de linter https://travis-ci.org/pagarme/pilot/builds/272586069#L468
> Fix eslint not failing Travis build

- webapp/stories/Switch/index.js
- webapp/stories/__snapshots__/storyshots.test.js.snap
Este PR remove uma `div` que estava dentro de um `p` no storybook! Remove um warning chato!
> switch: refactor p element to use div

- webapp/config/webpack.config.dev.js
- webapp/config/webpack.config.prod.js
- webapp/config/webpack.config.storybook.js
This adds cssnext to Storybook. To keep font book compatible with recent
browsers, we disable customProperties in cssnext configuration. Older IE
users still need to enable this flag to be able to see colors in components.
> chore: add cssnext to storybook

- webapp/src/components/Grid/index.js
- webapp/src/components/Grid/style.css
One can align items to the end of the column
Co-Authored-By:
Felquis Gimenes (@felquis)
Leonardo Felipe Nerone (@LeoNero)
Derek W. Stavis (@derekstavis)
> grid: add align end as option

- webapp/package.json
- webapp/yarn.lock
react-error-overlay 1.0.10 é a ultima versao antes da 2.0.0
> chore: fix yarn start

- webapp/src/components/Grid/index.js
- webapp/stories/__snapshots__/storyshots.test.js.snap
It will allow custom styling to these elements
and avoid unnecessary div elements.
```jsx
<Grid className={style.myAwesomeCustomSpacing}>
<Row className={style.itWillrockTheColumns}>
<Col className={style.someCustomHeight}>
Life is Good
</Col>
</Row>
</Grid>
```
:)
> grid: add className to Grid, Row and Col

- .travis.yml
Currently Percy doesn't have a way to be ran on open source projects.
Sharing the private project key isn't an option, as there isn't a way to generate a new key on Percy.
To fix this issue, make percy script in `.travis.yml` always return true.
> Fix Travis failing on PRs from forks because of Percy token

- .travis.yml
The `git diff` command used alone doesn't return an exit status. To make
git return an exit status when there are changes we need to use
`--exit-code`.
> Fix Git diff test not erroring CI

- webapp/src/components/Button/index.js
Button has only 3 possible type values. Proptypes should accept one of those 3 instead of just a `string`
> buttons: fix proptypes

- README.md
This refactors the README file to include the project brief.
As the text became longer to read, the first three quarters of project timeline were inverted and compressed inside a `<details>` tag.
Resolves #197
> Refactor README to add project brief

- .circleci/config.yml
- webapp/package.json
- webapp/yarn.lock
Currently Percy isn't being run on CircleCI. This makes visual regression
great again!
> Add percy to circleci

- webapp/yarn.lock
Rodei a branch master, e ao instalar as dependencias o yarn.lock ficou alterado. Mesmo que no PR https://github.com/pagarme/pilot/pull/311 ele mostra que passou no CI.
> percy: bump yarn.lock

- webapp/.gitignore
- webapp/README.md
- webapp/package.json
- webapp/yarn.lock
This module help us publish a preview of our work at Github Pages, to test this change checkout into the branch add-gh-pages, install dependencies, and run `yarn preview`.
> gh-pages: add yarn preview

- webapp/package.json
- webapp/yarn.lock
This adds a missing peer dependency that was emitting a warning when
installing packages.
> Add missing peer dependency

- webapp/src/components/CheckboxGroup/index.js
This is a performance improvement when various `CheckboxGroup` instances
are present on a single page.
> Add shouldComponentUpdate method to CheckboxGroup

- webapp/src/components/Dropdown/index.js
- webapp/stories/__snapshots__/storyshots.test.js.snap
when there's no select option with a empty value and the select doesn't
have a default value, the first one that is not disabled is selected, so
even if the `prop.value` is empty, the `select` value isn't
> dropdown: fix behaviour for default value

- webapp/src/components/DateSelector/DateSelector.test.js
- webapp/src/components/DateSelector/index.js
- webapp/stories/__snapshots__/storyshots.test.js.snap
@derekstavis 
This PR is only adding translation to the DateSelector component regarding issue #342. I want you to see if I am doing it correctly first, so I can work on the other components that also need translations.
---
With the current project setup, all components are respecting the global locale that is set for the entire application on [this file](https://github.com/pagarme/pilot/blob/master/webapp/src/locale/index.js). If I give the user the option to update the locale on a single component, the entire application will also change.
One solution for this is to put "days of the week" / "months" terms by hand inside the component and outside momentJS, maybe together with the strings props. Or we can leave the component "reading" the locale that is set on each particular project, as …
> date-selector: add strings prop for i18n

- .circleci/config.yml
- packages/pilot/package.json
we add cd process in ci/cd process on circleci build
we now have staging/production environments and this will work like these:
- we use git tag for control
- `v<MAJOR>.<MINOR>.<PATCH>-rc<RELEASE-CANDIDATE-NUMBER>` wil be send to staging in
https://beta.dashboard.stg.pagarme.net/latest/index.html or
https://beta.dashboard.stg.pagarme.net/versions/v0.1.0-rc12/index.html
- staging versions in /versions will be enabled in 30 days
- latest stage build will be stored in /latest/index.html
- `v<MAJOR>.<MINOR>.<PATCH>` will be send to production in
https://beta.dashboard.pagar.me
- producion process will send first in staging to be approved and later
will be sent to production.
- approval process will be done in circleci interface
> add: first deploy process in ci/cd

- packages/cockpit/src/transactions/details/index.js
- packages/cockpit/src/transactions/details/mocks/expectedResultAntifraud.json
- packages/cockpit/src/transactions/details/mocks/fromRequestsAntifraud.json
- packages/cockpit/src/transactions/details/result.js
- packages/cockpit/src/transactions/details/result.test.js
- packages/pilot/src/models/transactionOperationTypes.js
- packages/pilot/stories/pages/TransactionDetails/transactionMock.js
Add manual review step on transaction history as seen on the image below:
PS: The elliptical item enumeration is related to https://github.com/pagarme/pilot/issues/627
> Add review step to transaction details

- packages/pilot/src/containers/Filter/index.js
Garantir que o `Filter` funcione com apenas um 'element' de dentro das 'children'.
> Filter: fix children map

- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/components/SidebarSections/index.js
- packages/pilot/src/components/SidebarSections/style.css
- packages/pilot/src/components/SidebarSummary/index.js
- packages/pilot/src/components/SidebarSummary/style.css
- packages/pilot/src/containers/Sidebar.js
- packages/pilot/src/pages/Account/actions/epic.js
- packages/pilot/src/pages/Account/actions/index.js
- packages/pilot/src/pages/Account/actions/reducer.js
- packages/pilot/src/pages/LoggedArea/Sidebar.js
- packages/pilot/src/pages/LoggedArea/index.js
- packages/pilot/src/pages/LoggedArea/routes.js
- packages/pilot/src/pages/Withdraw/actions/index.js
- packages/pilot/src/pages/Withdraw/index.js
- packages/pilot/stories/components/SidebarSections/index.js
- packages/pilot/stories/components/SidebarSummary/index.js
- packages/pilot/stories/components/index.js
- Add `SidebarSummary`
- Add `SidebarSections`
- Add epic to update Sidebar Values when a withdraw is done
- Refactor sidebar to add the new components
- Add `back to the version 1.0` translation
- Resolves https://github.com/pagarme/pilot/issues/730
> sidebar: add summary and sections

- packages/pilot/src/containers/AddRecipient/BankAccountStep/AddAccount/index.js
- packages/pilot/src/containers/AddRecipient/BankAccountStep/SelectAccount/index.js
- packages/pilot/src/containers/AddRecipient/BankAccountStep/index.js
- packages/pilot/src/containers/AddRecipient/BankAccountStep/style.css
- packages/pilot/stories/containers/AddRecipient/BankAccountStep/AddAccount/index.js
- packages/pilot/stories/containers/AddRecipient/BankAccountStep/SelectAccount/index.js
- packages/pilot/stories/containers/AddRecipient/BankAccountStep/index.js
- packages/pilot/stories/containers/index.js
Adiciona o passo de selecionar/cadastrar uma conta bancária, para o fluxo de cadastrar um novo recebedor na página de recebedores.
- Se o recebedor não tiver nenhuma conta cadastrada, o dropdown junto com o switch não devem ser renderizados, mostrando apenas a opção de "adicionar uma conta".
> recipient: add bank account step

- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/pages/LoggedArea/routes.js
- packages/pilot/src/pages/Withdraw/index.js
Adiciona alerta quando o id de recebedor passado na url nao existe.
Nao creio que faz sentido verificar se existe ou nao recebedor padrao (ver comment do Relampago Marquin)
Closes #708
> withdraw: fix empty recipients

- packages/pilot/src/validation/required.js
A validação de `require` não atendia a todos os cenários que precisamos
| Case        | Old            | Fixed         |
| ------------- | ---------------| -------------- |
| []               | `false`        | `message` |
| {}               | `false`        | `message` |
| ``               | `message` | `message` |
| null            | `message` | `message` |
| undefined  | `message` | `message` |
| Case        | Old            | Fixed         |
| ------------- | ---------------| -------------- |
| 0              | `message` | `false`        |
| [1]            | `false`        | `false`        |
| {a: 0}        | `false`        | `false`       |
| true          | `false`        | `false`       |
| false         | `message` | `false`       |
> validation: fix require validation

- .circleci/config.yml
- Add `yarn lint` to packages/pilot 'cause there are CSS and JS errors passing on CircleCI.
> circle-ci: add yarn lint to packages/pilot

- packages/pilot/package.json
- yarn.lock
Bump `react-vanilla-form` to version 0.6.1
> Update react-vanilla-form to 0.6.1

- packages/pilot/src/containers/RecipientDetailInfo/index.js
- packages/pilot/src/containers/RecipientDetailInfo/style.css
- packages/pilot/stories/containers/RecipientDetailInfo/index.js
- packages/pilot/stories/containers/index.js
Renderiza a terceira aba de `Mais Informações` da página de `Detalhes de Recebedores`
- [Issue 264](https://github.com/pagarme/caesar/issues/264) 
- [Zeplin](https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5b69e3371f63306dac625f50)
> recipient-detail-info: add component

- packages/pilot/src/components/BalanceSummary/index.js
- packages/pilot/src/components/BalanceTotalDisplay/index.js
- packages/pilot/src/components/PendingRequests/index.js
- packages/pilot/src/containers/Balance/index.js
- packages/pilot/src/containers/RecipientDetails/RecipientBalance/index.js
- packages/pilot/src/containers/RecipientDetails/RecipientBalance/style.css
- packages/pilot/stories/components/BalanceSummary/index.js
- packages/pilot/stories/components/BalanceTotalDisplay/index.js
- packages/pilot/stories/components/PendingRequests/index.js
- packages/pilot/stories/containers/RecipientDetails/RecipientBalance/index.js
- packages/pilot/stories/containers/index.js
Adiciona o componente de extrato do recebedor, que vai compor uma das abas da página de Detalhes do Recebedor.
[Layout do zeplin](https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5b68ca9380c45b7de90ed526)
> Extrato do Recebedor

- packages/pilot/src/components/CurrencyInput/index.js
Esse PR remove o callback utlizado no `setState` dentro do `handleChange` e também remove o método obsoleto `componentWillReceiveProps`
> currency-input: remove callback on setState

- .circleci/config.yml
Este PR adiciona `index.html` nas variaveis de ambiente `REACT_APP_LIVE_URL` e `REACT_APP_TEST_URL` no ambiente de stage, isso é necessário para o redirecionamento correto
este PR não tem impacto visual
este PR altera atribuição das variáveis `REACT_APP_LIVE_URL` e `REACT_APP_TEST_URL` no fluxo de deploy
> chore: add url postfix in circle ci variables

- packages/pilot/package.json
- packages/pilot/src/components/PaymentCard/style.css
- packages/pilot/src/components/PendingRequests/style.css
- packages/pilot/src/containers/Account/style.css
- yarn.lock
Este PR atualiza a dependencia `react-scripts-former-kit `  para a versão `0.1.2`
este PR não tem impacto visual
atualiza a versão do react scripts, corrigindo o bug da versão atual da dependencia  `react-scripts-former-kit ` que busca as regras de lint erradas
> update react-scripts-former-kit to 0.1.2

- packages/pilot/public/locales/pt/translations.json
- Corrige um erro de português em `Boas-vindas`
- Troca a exclamação por ponto final no subtitle
[insira o screenshot aqui]
<!-- Insira o layout do Zeplin des
> self-register: fix translate message

- packages/cockpit/src/company/register/index.js
Estamos removendo o parâmetro `should_activate` na request que o cockpit envia pois não usamos na API
> create-company: remove should_activate parameter

- packages/pilot/stories/containers/SelfRegister/index.js
Remove a função de `translate` nos storybook do containers de `self-register`, assim seguindo o padrão da Pilot.
> self-register: remove translate function

- packages/pilot/src/pages/Root.js
Adiciona a feature flag na rota `/account/register`, habilitando-a somente caso tenha no local storage `feature_flag_self_register` como `'true'`.
Para ativar, basta inserir no console:
```js
localStorage.setItem('feature_flag_self_register', 'true')
```
> self-register: add feature flag to enable self register route

- README.md
This PR fixes an issue where "High-order components" was incorrectly
used.
In fact, this is a side-effect of this PR, which refactors the section
"Estrutura do projeto" so it provides more information about each
directory and why they exists.
This also fixes references from "a Pilot" to "o Pilot", since Pilot
refers to "the project", which is male in Portuguese -- "O projeto
Pilot".
> Correções de erros e melhorias no README

- packages/pilot/src/containers/Settings/Company/TeamInfoTab/TeamManagement/index.js
- packages/pilot/src/pages/Refund/Refund.js
- packages/pilot/src/pages/Reprocess/index.js
- packages/pilot/src/pages/Transactions/Details/Details.js
Esse PR refatora alguns componentes para aparecer a transição de saída ao fechar o modal. Como alguns componentes tinham validação e sumiam do DOM rapidamente, tive que refatorar para aparecer que o `closeTimeoutMS` acontecesse. Esse PR é relacionado com https://github.com/pagarme/former-kit-skin-pagarme/pull/148 e https://github.com/pagarme/former-kit/pull/204. 
- Vá para a branch `master` em former-kit-skin e former-kit
```
git checkout master
```
- Crie um link para os repositórios former-kit-skin e former-kit
```
yarn link
```
- Dê um link dentro do former-kit-skin-pagarme
```
yarn link former-kit
```
- Dê um link dentro da Pilot
```
yarn link former-kit
yarn link former-kit-skin
```
- Rode normalmente o storybook da former-kit e/ou da Pilot
```
yarn storybook
```
> Modal: refatorando o flow da animação do modal

- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/containers/Filter/index.js
- packages/pilot/src/containers/Filter/style.css
Espaço entre itens do filtro. Esse PR depende de uma modificação no espaço entre `.actions` de cards e nas cores de placeholder de input em: https://github.com/pagarme/former-kit-skin-pagarme/pull/146
**Depends on https://github.com/pagarme/former-kit-skin-pagarme/pull/150** 
`zeplin`: https://zpl.io/VK0ZzR7
> Filter: update spacing and flexbox

- packages/pilot/src/containers/CreateTransaction/Payment/CreditCard.js
- packages/pilot/src/containers/CreateTransaction/Payment/style.css
- packages/pilot/src/validation/creditCard.js
- packages/pilot/src/validation/cvv.js
- packages/pilot/src/validation/sameOrFutureDate.js
- packages/pilot/stories/components/CreditCardForm/index.js
- packages/pilot/stories/components/index.js
Este PR adiciona o formulário de cartão de crédito no step de pagamentos em adicionar transação.
- Faça checkout para esta branch `git checkout add/transaction-payment-credit-form`
- Rode o storybook: `yarn storybook`
> create-transaction: add payment credit card form

- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/components/CaptureDetails/index.js
- packages/pilot/src/containers/Capture/Form/index.js
- packages/pilot/src/containers/Capture/Form/style.css
- packages/pilot/src/containers/Capture/Result/index.js
- packages/pilot/src/containers/Capture/Result/style.css
- packages/pilot/src/containers/Capture/index.js
- packages/pilot/stories/components/CaptureDetails/index.js
- packages/pilot/stories/components/index.js
- packages/pilot/stories/containers/Capture/Form/index.js
- packages/pilot/stories/containers/Capture/Result/index.js
- packages/pilot/stories/containers/Capture/index.js
- packages/pilot/stories/containers/index.js
Este PR adiciona o modal para captura de transações. A ideia é que seja possível capturar ambas as transações criadas pelo Checkout (Encryption Key) como aquelas criadas diretamente pela API (API Key). Sendo as distinções dos comportamentos:
- Encryption Key: Valor não pode ser alterado, pois este é aplicado no frontend com o uso do Checkout (a nossa API também não permite capturar um valor diferente do autorizado pelo front).
- API Key: Permitir que o usuário informe o valor a ser capturado, sendo possível fazer a captura parcial.
relacionado a issue #869
- Captura editável (API Key)
- Captura não editável (Encryption Key)
- Sucesso
- Layout de captura editável
- Layout de captura não editável
- Layout de captura bem sucedida
> Transações: Modal de Captura

- packages/pilot/src/containers/Capture/Form/index.js
Este PR adiciona o link para a página que conterá o texto de alerta ao usuário sobre a captura de transações criadas pelo Checkout Pagar.me.
O texto ficará em uma página em nossa documentação (acessível somente via url diretamente), mas por enquanto deixei o texto em um gist para revisarmos:
https://gist.github.com/vagnervst/781adafc855fd9a51a94417731d9fe2f
> transaction: add token capture disclaimer link

- packages/pilot/src/containers/Capture/Form/index.js
Como a captura manual de transações criadas pelo Checkout Pagar.me necessita de atenção à alguns detalhes, criei uma página na documentação para fornecer mais detalhes ao cliente.
> Captura manual - Adiciona link para a documentação

- packages/pilot/src/pages/Recipients/Search/Search.js
Foi adicionado no Recebedor um campo denominado `external_id`, com isso a Tela de Listagem de Recebedores deverá ser capaz de fazer busca pelo `external_id`
O Campo `external_id` não tem padrão, ou seja, é um campo livre, assim dificulta a identificação para realizar as buscas, pois como os Recebedores não são indexado pelo `Elastic Search` é necessário discriminar onde deve ser buscado.
Hoje os campos de `id` e `bankAccount` são identificados seguindo o padrão de como eles são gerados (ex: começar com `re_` ou ser apenas números) no caso do `external_id` a solução será: caso não caia em nenhum dos cases, realizar a busca tanto no `name` quanto no `external_id`, assim retornando o resultado dos dois.
> Recipients: Adicionar busca pelo external_id

- packages/pilot/src/components/CustomerCard/index.js
- packages/pilot/src/components/CustomerCard/style.css
- packages/pilot/src/components/DetailsHead/style.css
- packages/pilot/src/components/Event/style.css
- packages/pilot/src/components/PaymentBoleto/style.css
- packages/pilot/src/components/PaymentCard/index.js
- packages/pilot/src/components/PaymentCard/style.css
- packages/pilot/src/components/Property/style.css
- packages/pilot/src/components/RecipientSection/index.js
- packages/pilot/src/components/RiskLevel/style.css
- packages/pilot/src/components/TotalDisplay/style.css
- packages/pilot/src/components/TransactionDetailsCard/index.js
- packages/pilot/src/components/TransactionDetailsCard/style.css
- packages/pilot/src/containers/RecipientList/index.js
- packages/pilot/src/containers/RecipientList/style.css
- packages/pilot/src/containers/TransactionDetails/index.js
- packages/pilot/src/containers/TransactionDetails/style.css
- packages/pilot/src/pages/Transactions/Details/Details.js
- packages/pilot/src/validation/matchToMediaQuery.js
Adiciona um botão de exportar dados detalhados da transação 
Layout obtido:
[Pagar.me Dashboard.pdf](https://github.com/pagarme/pilot/files/2780239/Pagar.me.Dashboard.pdf)
Layout desenhado pelo @flaviolee 
[layout_exportacao.pdf](https://github.com/pagarme/pilot/files/2780231/layout_exportacao.pdf)
https://zpl.io/V0Z7Ggx
- faça checkout para esta branch: `git checkout add/transactions-details-export-data`
- rode no diretório do pilot: `yarn start`
- Na página de detalhes da transação selecione a opção de exportar
> transactions-details: add export data

- packages/pilot/src/pages/Withdraw/index.js
Esta release corrige  o envio da request em `/transfer` na pagina de saque. Passando para a api o `valor_requisitado - taxa`
- Erro ao gerar saque #1118 
- acessar a url do release candidate
- efetuar login
- sacar o valor máximo disponível
- verificar se foi possível realizar o saque com sucesso
> release v0.9.1

- packages/cockpit/src/transactions/search/result.js
- packages/cockpit/src/transactions/search/statusOrder.js
A ordenação das legendas das transações estava sendo feita de acordo com o nome do status em inglês. Esse PR corrige esse problema ordenando as legendas para PT-BR.
**Esse PR só resolve a parte de Front-end da ordenação, levando os itens de <TransactionSearch> estarem sempre ordenados por ordem alfabética na página, e não por completo. O fix completo deveria ser na API.**
- Rode a Pilot em `packages/pilot`
```
yarn start
```
- Filtre os resultados para ordem crescente ou decrescente dentro da página de Transações e veja se está indo em ordem alfabética em PT-BR.
> Transactions: Order status legend

- packages/pilot/src/containers/AddRecipient/BankAccountStep/index.js
- packages/pilot/src/containers/AddRecipient/ConclusionStep/index.js
- packages/pilot/src/containers/AddRecipient/ConfigurationStep/index.js
- packages/pilot/src/containers/AddRecipient/ConfirmStep/index.js
- packages/pilot/src/containers/AddRecipient/ErrorStep/index.js
- packages/pilot/src/containers/AddRecipient/IdentificationStep/index.js
- packages/pilot/src/vendor/googleTagManager.js
Este PR faz com que um evento customizado seja emitido para o Google Tag Manager a cada passo do formulário de adicionar recebedores, fazendo com que o Google Analytics considere cada passo como uma visualização de página.
Isto permitirá que seja feito tracking do formulário, criando um funil de conversão.
Utilize o modo de visualização do Google Tag Manager para ver os eventos sendo disparados, e verifique se o evento `virtualPageView` é disparado a cada passo do fluxo de cadastro de recebedor.
Também cheque o relatório de páginas sendo acessadas em tempo real do Google Analytics e verifique se existem page views com URLs do tipo `/virtual/recipient/add/`.
> Adiciona Virtual Page Views nos passos de cadastro de recebedor

- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/containers/AddRecipient/ConfigurationStep/index.js
- packages/pilot/src/containers/RecipientDetails/Balance/index.js
- packages/pilot/src/pages/Recipients/Detail/index.js
- packages/pilot/src/pages/Recipients/Detail/style.css
- packages/pilot/stories/containers/AddRecipient/ConfirmStep/index.js
- packages/pilot/stories/containers/RecipientDetails/index.js
Este PR visa a implementação do componente `Snackbar`, adicionado recentemente ao `former-kit` na versão `1.1.0`, à tela de Detalhes do recebedor.
Comentário sobre o cherry-pick conforme o card: https://github.com/pagarme/caesar/issues/329#issuecomment-470676381
https://github.com/pagarme/caesar/issues/329
Neste PR estou aproveitando para deixar o `former-kit`atualizado em sua última versão: `1.2.0`
- git clone no projeto
- `yarn install` para baixar as dependências
- seguir os checks inseridos em `Checklist` para testar a aplicação.
> Add: Snackbar component

- packages/cockpit/src/transactions/search/query.js
- packages/cockpit/src/transactions/search/query.test.js
- packages/pilot/src/containers/TransactionsList/tableColumns.js
Na versão 2017-08-28 da API, os números de documento passaram a ser registrados em um array em customer, gerando uma quebra de interface com as versões anteriores. Além de não filtrar no campo de busca por CPF. Esse PR conserta esses erros.
Foi utilizado o mesmo tratamento da página de detalhes da transação, que apresenta o número de documento corretamente para qualquer versão da API.
- Vá para branch `refactor/transaction-search-cpf`
- Rode `yarn build` no `packages/cockpit`
- Rode `yarn start` para abrir a pilot
- Confira na página `Transações` se o CPF do customer aparece em cada transação realizada. 
- Confira se alguma transação pode ser filtrada por CPF ou CNPJ, com pontos ou sem pontos. Se sim, é isso aê! :tada:
> transactions-list: refactor table columns and filter

- packages/pilot/src/containers/Sidebar/index.js
- packages/pilot/src/pages/LoggedArea/index.js
- packages/pilot/src/pages/LoggedArea/routes.js
Este PR comenta alguns códigos do `Sidebar` container e algumas rotas do arquivo de `routes.js`. Estes códigos comentados são para o lançamento da dash de recebedores para teste que será enviado para alguns clientes. Dessa forma acreditamos que direcionaremos o usuário a focar somente nas telas novas de Recebedores (Listagem, Adição e Detalhes de recebedores). E com isso os feedbacks são direcionados para essas três funcionalidades.
Segue link do Card: https://github.com/pagarme/caesar/issues/342
- `git clone` neste repositório
- `yarn install` para puxar todas as dependências
- `yarn start` para rodar a tela local
> Sidebar: update Sidebar

- packages/pilot/src/containers/TransactionDetails/index.js
- packages/pilot/src/pages/Transactions/Details/Details.js
Este PR adiciona a possibilidade de a página de detalhe de transação imprimir quando ser carregada usando a query string `print=true` na URL.
1. Acesse a pilot com a seguinte url: `http://localhost:3000/#/account/login?session_id=<session id>&redirect=/transactions/<transaction id>?print=true`
> transaction: add hability to export based on query string from dashboard

- packages/cockpit/src/bulkAnticipations/index.js
- packages/pilot/src/containers/Balance/index.js
Este PR corrige o card de `Solicitações Recentes` na tela de extrato, que atualmente exibe o valor sem descontar a taxa de transferência (quando automática)
- Resposta da API
- Exibição na Pilot
1. Crie uma antecipação habilitando a transferência automática
2. Confirme se o valor líquido no formulário de antecipação é igual ao valor exibido em extrato
> Extrato - Corrige valor líquido de solicitações recentes

- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/containers/Filter/index.js
- packages/pilot/src/containers/RecipientDetails/index.js
- packages/pilot/src/containers/RecipientTable/index.js
- packages/pilot/src/containers/RecipientTable/statusLegend.js
- packages/pilot/src/containers/RecipientTable/tableColumns.js
- packages/pilot/src/models/recipientStatusLegends.js
- packages/pilot/src/pages/Recipients/Search/Search.js
- packages/pilot/src/pages/Recipients/Search/reducer.js
- packages/pilot/stories/containers/RecipientDetails/index.js
Este PR corrige alguns problemas encontrados na dash de recebedores. Os erros foram detectados um pouco antes de lançarmos o segundo link para teste em cliente. Ele junta erros encontrados internamente e feedbacks de nossos clientes.
Este PR faz parte deste card: https://github.com/pagarme/caesar/issues/361
Guardando o valor de busca no `state` para que a busca não seja perdida após a mudança de tela:
Traduzindo o status:
- `git clone` deste repo
- `yarn` para baixar todas as dependências
- `yarn start` para rodar local
> PR: Fix de small issues encontradas na Dash de Recebedores

- packages/pilot/public/locales/pt/translations.json
Este PR visa corrigir o arquivo de translate. Mudar o termo `Volume antecipado` para `Volume antecipável`.
Faz parte desse card: https://github.com/pagarme/caesar/issues/363
- `git clone` nesse repo
- `yarn` para instalar as dependências
- `yarn start` para rodar local
> antecipation: update translate

- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/errors/index.js
- packages/pilot/src/errors/pendingRiskAnalysis.js
- packages/pilot/src/pages/Account/actions/epic.js
Para validar esse pull request acesse os links onde esta versão foi publicada
Essa release tem como objetivo principal adicionar o erro personalizado para companies do tipo `self_register` com o status `pending_risk_analysis`
- errors: add pending risk analysis error #1256
- acessar a pilot com uma company que foi gerada a partir do cadastro do autocredenciamento com o template de `self_register`
- verificar se a modal com o erro customizado avisando para o cliente que está aguardando aprovação é exibida
resolves #1258
> release 0.14.2 - 17/06/2019

- packages/pilot/src/pages/Account/actions/epic.js
Atualmente temos um problema com o login de um lojista que vem como `self_register`, a primeira vez que ele loga é mostrado um modal informando que faltam alguns detalhes, na segunda vez esse modal não é mostrado.
1. Crie uma conta com o token de self_register e confirme a sua conta.
2. Inicie a pilot em modo live: `env REACT_APP_API_ENVIRONMENT=live yarn start`
3. Faça login usando sua conta.
> account: refactor to handle with autocred companies.

- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/containers/RecipientDetails/Config/BankAccountContent/index.js
- packages/pilot/src/containers/RecipientTable/NotFoundMessage.js
- packages/pilot/src/containers/RecipientTable/index.js
- packages/pilot/src/containers/RecipientTable/style.css
- packages/pilot/src/pages/ErrorBoundary/ErrorBoundary.js
- packages/pilot/src/pages/Recipients/Detail/index.js
- packages/pilot/src/pages/Recipients/Search/Search.js
Este PR atualiza algumas funcionalidades dos fluxos das telas de Recebedores/Marketplaces. Alguns problemas foram encontrados no PR #1371 e este em questão busca resolvê-los para que a Home de Recebeodres possa ser mergeada na master.
Este PR faz parte da seguinte issue: [Caesar #385](https://github.com/pagarme/caesar/issues/385)
Validação:
Mensagem de erro ao usuário sem permissão:
- `git clone` deste respositório
- `yarn` para instalar todas as dependências
- `yarn start` para rodar local
Para testar as funcionalidades, reproduza os problemas que os checks em _Checklist_  estão resolvendo.
> PR de fixes da release/v0.19.0-rc1

- packages/cockpit/src/transactions/details/isReprocessable.test.js
- packages/pilot/src/components/DetailsHead/index.js
- packages/pilot/src/containers/TransactionDetails/index.js
- packages/pilot/src/pages/Reprocess/index.js
- packages/pilot/src/pages/Transactions/Details/Details.js
Esta release é referente a fix no fluxo de reprocessamento. 
Foi criado um processo de retentativa na atualização da pagina que faz consulta ao elastic search. Este fix foi necessário devido a demora ao indexar.
- acessar a pilot no link da rc
- acessar uma transação que pode ser reprocessada
- reprossar a transação
- no passo de sucesso clicar no botão (x) fechar da modal
- o botão de reprocessar deve ficar desabilitado e carregando até obter a informação
- Limpar dados do estado da modal de reprocessamento após fechar a modal #1415
resolves #1422
> Release v0.20.1

- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/containers/TransactionDetails/index.js
- packages/pilot/src/pages/Transactions/Details/Details.js
- packages/pilot/stories/pages/TransactionDetails/index.js
Este PR altera os labels das `actions` do container `Detalhes da Transação`  para obterem seus títulos de nossas traduções.
- Entre na branch `refactor/transaction-details`
- Vá até `pilot/packages/pilot` e rode yarn start.
- Vá até `Transações` e selecione as que podem executar as ações:
- `Reprocessar` (Ao reprocessar e fechar o modal, o botão deve mudar o título para `Reprocessando`), `Exportar`, `Capturar`, `Estornar` e `Gerar boleto`.
- Cheque se os botões estão recebendo seus títulos corretamente.
> Refactor de labels do container Detalhes da Transação

- packages/pilot/src/validation/protocol.js
Atualmente, quando adicionamos um novo recebedor, não é possível adicionar uma url válida apenas com `www`, sem `http` ou `https`.
Este PR atualiza a validação de protocolo tornando possível a adição de um site com um `www`. Exemplo: `www.site.com.br`
Issue relacionada: [Caesar #433](https://github.com/pagarme/caesar/issues/433)
Caso de erro:
Casos de acerto:
- `git clone` para clonar este repositório
- `yarn` para instalar todas as dependências
- `yarn start` para rodar local
- Ir em _Recebedore_ -> clicar no botão de _Adicionar Recebedor_ -> incluir mais informações -> testar as seguintes entradas:
- `www.site.com.br`
- `http://www.site.com.br`
- `https://www.site.com.br`
- `http://site.com.br`
> PR: update URL validation

- packages/cockpit/src/transactions/reprocess/cleanTransaction.js
- packages/cockpit/src/transactions/reprocess/cleanTransaction.test.js
Após o redirecionamento dos usuários da dashboard para a pilot, notamos que algumas transações falhavam durante reprocessar. Investigando, chegamos a conclusão que isso só ocorria ao reprocessar transações com o antifraude ativo e originárias da api versão `2013-03-01`.
Isso ocorre devido a diferença na estrutura de requisição feita pela api `2013-03-01`, que exige que as informações do `customer` estejam preenchidas (não aceita apenas o customer.id).
Reprocessar uma transação com antifraude ativo e com a versão da api 2013-03-01. O comportamento esperado é que a transação seja reprocessada com sucesso.
> cockpit: fix reprocess transactions payload

- packages/cockpit/src/balance/mocks/operations/expected.json
- packages/cockpit/src/balance/mocks/payables/expected.json
- packages/cockpit/src/balance/operations/buildRequest.js
- packages/cockpit/src/balance/operations/operations.js
- packages/cockpit/src/balance/operations/operations.test.js
- packages/cockpit/src/balance/operations/shared.js
- packages/cockpit/src/balance/operations/shared.test.js
- packages/cockpit/src/balance/total/buildRequest.js
- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/components/Operations/operationsTableColumns.js
- packages/pilot/src/models/operationTypes.js
Atualmente não temos previsto no cockpit as transferências para conta Bradesco. Este PR adiciona em nossa chamada `operations` as validações necessárias para que mostremos este tipo de transferência de `type: "credito_em_conta"`.
1. Crie um recebedor com conta bancária Bradesco:
```bash
curl -X POST \
https://api.pagar.me/1/recipients \
-H 'content-type: application/json' \
-d '{
"anticipatable_volume_percentage": "85", 
"api_key": "<api_key>", 
"automatic_anticipation_enabled": "true", 
"transfer_day": "5", 
"transfer_enabled": "true", 
"transfer_interval": "weekly",
"bank_account": {
"agencia": "0932", 
"agencia_dv": "5",
"bank_code": "237", 
"conta": "58054", 
"conta_dv": "1", 
"document_number": "26268738888", 
"legal_name": "API TEST BANK ACCOUNT"
}
}'
```
2. Adicione nele uma …
> Extrato - Corrige exibição de transferências bancárias

- packages/pilot/src/containers/RecipientDetails/Config/HelpModal/index.js
- packages/pilot/src/containers/RecipientDetails/Config/index.js
- packages/pilot/stories/containers/RecipientDetails/Config/index.js
A @miglsoares notou um erro em nosso percy à respeito da tela de configuração de recebedores. O que ocorreu foi que criamos uma nova prop em um dos componentes utilizado nesta tela, porém não passamos esta prop na story do componente, causando um erro no storybook. Este PR corrige isto.
1. Utilize o storybook e vá para a story `Containers|Page Containers|Recipient Configuration`
> Recebedores - Corrige storybook da tela de configurações

- packages/pilot/src/pages/Account/actions/epic.js
- packages/pilot/src/vendor/appcues.js
- packages/pilot/src/vendor/setCompany.js
Adiciona a propriedade `company.type` na função `setCompany` que envia dados para o AppCues. 
Precisamos desta informação no AppCues para conseguir filtrar quais mensagens devem aparecer, dependendo do tipo da company.
Não houve alterações visuais :heavy_check_mark: 
Não houve alterações visuais :heavy_check_mark: 
Não houve alterações visuais :heavy_check_mark: 
Não há notas de deploy :heavy_check_mark: 
* Verificar que o `companyType` está sendo enviado na requisição para o AppCues.
> chore: send company type to appcues

- packages/cockpit/src/transactions/details/mocks/expectedResultAntifraud.json
- packages/cockpit/src/transactions/details/mocks/expectedResultBoleto.json
- packages/cockpit/src/transactions/details/mocks/expectedResultFraudCovered.json
- packages/cockpit/src/transactions/details/mocks/expectedResultMock.json
- packages/cockpit/src/transactions/details/mocks/fromRequestsFraudCovered.json
- packages/cockpit/src/transactions/details/result.js
- packages/cockpit/src/transactions/details/result.test.js
- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/components/RecipientSection/installmentTableColumns.js
- packages/pilot/src/containers/TransactionDetails/index.js
- packages/pilot/src/pages/Transactions/Details/Details.js
- packages/pilot/stories/pages/TransactionDetails/index.js
Esse PR adiciona o valor da garantia de chargeback no "Total de Saídas", "Valor Líquido", "Taxas" e total de taxas.
Adiciona aos mocks o `fraud_coverage_fee`, para que seja possível calcular o `fraud_coverage_amount` (soma de todos os `fraud_coverage_fee`).
Adiciona ao `costs` a propriedade `taxes`, que é a soma do `mdr` e `fraud_coverage_amount`.
https://github.com/pagarme/protection/issues/740
1) Ter uma company com garantia ativa.
2) Criar uma transação paga com cartão de crédito
> Adiciona os valores de garantia de chargeback ao detalhe da transação

- packages/cockpit/src/transactions/details/mocks/expectedResultAntifraud.json
- packages/cockpit/src/transactions/details/mocks/expectedResultBoleto.json
- packages/cockpit/src/transactions/details/mocks/expectedResultFraudCovered.json
- packages/cockpit/src/transactions/details/mocks/expectedResultMock.json
- packages/cockpit/src/transactions/details/mocks/fromRequestsFraudCovered.json
- packages/cockpit/src/transactions/details/result.js
- packages/cockpit/src/transactions/details/result.test.js
- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/components/RecipientSection/installmentTableColumns.js
- packages/pilot/src/containers/TransactionDetails/index.js
- packages/pilot/src/pages/Account/actions/epic.js
- packages/pilot/src/pages/Transactions/Details/Details.js
- packages/pilot/src/vendor/appcues.js
- packages/pilot/src/vendor/setCompany.js
- packages/pilot/stories/pages/TransactionDetails/index.js
Esta versão contem pequenas alterações no envio de dado ao appcues e visualiação de valores na pagina de detalhes da transação
- Adiciona o campo type da company no envio de dados para o appcues
- Adiciona os valores de garantia de chargeback na página de detalhes da transação
- Ter uma company com garantia ativa.
- Criar uma transação paga com cartão de crédito
- verificar se os valores informados no detalhe da transação criada constam os valores de garantia
- chore: send company type to appcues #1542
- Adiciona os valores de garantia de chargeback ao detalhe da transação #1541
resolves #1547
> Release v0.21.7

- packages/pilot/src/components/ApiKey/index.js
- packages/pilot/src/vendor/fullStory.js
esste pr:
- adiciona a classe `fs-block`na exibição de api-keys
- altera o envio das datas de criação do usuário e company para o tipo `date` no fullstory
- https://github.com/pagarme/greenphoenix/issues/169
- baixar a branch `add/fullstory-block`
- executar a pilot
- navegar para tela de configuração
- verificar se os elementos pai da exibição das api keys contem a classe `fs-block`
> Add fullstory block

- packages/cockpit/src/transactions/details/isReprocessable.js
- packages/cockpit/src/transactions/details/isReprocessable.test.js
Adiciona dois dias extras a janela de reprocessamento.
obs: coloquei a tag de blocked porque apesar do PR estar pronto, só poderemos deployá-lo no meio da próxima semana.
> cockpit: update reprocessment date window

- packages/pilot/src/containers/PaymentLinks/Header/index.js
- packages/pilot/src/containers/PaymentLinks/Header/style.css
- packages/pilot/stories/components/PaymentLinkHeader/index.js
- packages/pilot/stories/components/index.js
Este PR adiciona o componente Header que será utilizado na lista de links de pagamento
1. Rode o storybook com `cd packages/pilot && yarn storybook`
2. Acesse a story Custom Components -> PaymentLinkHeader
> Links de pagamento - Adiciona componente header

- packages/cockpit/src/balance/mocks/operations/expected.json
- packages/cockpit/src/balance/mocks/operations/received.json
- packages/cockpit/src/balance/operations/operations.js
- packages/cockpit/src/balance/operations/operations.test.js
- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/components/Operations/operationsTableColumns.js
- packages/pilot/src/models/operationTypes.js
Essa release corrigi um problema na exibição na reversão de estorno
Link da versão corrente de staging com esta correção.
https://beta.dashboard.sandbox.stg.pagarme.net/versions/v0.21.11-rc3/index.html#/account/login
Tag corrente: https://github.com/pagarme/pilot/releases/tag/v0.21.11-rc3
- Operações de reversão de estorno causam erro no Extrato #1565
- Extrato - Adiciona compatibilidade com reversão de estorno #1566
- Reversão de Estorno - Correções #1573
- Reversão de Estorno - Correções #1569
- verificar se as operação de refund reversal estão aparecendo corretamente no extrato
resolves #1567
> release v0.21.11

- packages/pilot/package.json
- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/components/FakeLoader/index.js
- packages/pilot/src/components/FakeLoader/styles.css
- packages/pilot/src/components/Spinner/index.js
- packages/pilot/src/components/Spinner/styles.css
- packages/pilot/stories/components/FakeLoader/index.js
- packages/pilot/stories/components/index.js
- yarn.lock
Conforme detalhado na issue https://github.com/pagarme/pilot/issues/1579, estamos partindo para a segunda etapa do fluxo de Onboarding, etapa na qual serão mostradas algumas perguntas com a expectativa que nosso cliente as respondam e nos forneçam insumos para melhorarmos o seu processo de onboarding na pagar.me.
Neste PR está adicionado o componente `FakeLoader`. A função deste componente é simular a construção de uma dashboard após o usuário responder todas as perguntas. A ideia é que com o _loader_, ocorra um alinhamento entre a expectativa do usuário com a dashboard.
O componente `FakeLoader` é composto de um Spinner e três steps. 
Cada step irá mostrar uma mensagem (sendo que as imagens podem ser visualizadas no Figma), sendo que cada step deve demorar 1.5 segundos.
Após os três …
> Adicionar FakeLoader

- packages/pilot/src/pages/Account/actions/epic.js
Notou-se que para alguns clientes que já transacionaram na pilot e foram criados a mais de 30 dias, o emptyState estava sendo exibido. A issue https://github.com/pagarme/credenciamento/issues/477 fornece mais detalhes sobre o ocorrido.
Isto está fugindo a seguinte regra `A página do EmptyState padrão deve ser mostrado para clientes que foram cadastrados a menos de um mês ou que ainda não transacionaram.`, postada na issue https://github.com/pagarme/pilot/issues/1570.
Ao realizarmos a investigação, ficou um pouco nebuloso sobre qual é a raiz do problema. Isto porque a rota `/search` da API não possui logs da resposta, o que acaba dificultando no entendimento do problema. Entretanto, pelo que debuguei, está é a única fonte que pode estar causando este comportamento, visto que por padrão, o …
> Refactor alreadyTransacted flag

- packages/pilot/src/containers/Onboarding/index.js
Conforme identificado pelo @vagnervst [neste comment](https://github.com/pagarme/pilot/pull/1592#issuecomment-608088241), não está sendo resetado o estado `others` quando uma nova pergunta chega.
Isto acaba causando com que todas as perguntas enviem o mesmo estado, o que no caso é o desejado.
Desta forma, este PR adiciona um `useEffect` para reiniciar o estado de `others` toda vez que houver uma nova pergunta.
> onboarding: update others state on new question

- packages/pilot/src/pages/Account/actions/epic.js
- packages/pilot/src/pages/Withdraw/index.js
- Tentar logar com uma company cuja capability `allow_dashboard_login` como `false`. Não deverá ser permitido.
1. Crie uma conta bancária de código `237`:
```bash
curl -L -X POST 'https://api.pagar.me/1/bank_accounts' \
-H 'content-type: application/json' \
--data-raw '{
"agencia": "0932", 
"agencia_dv": "5", 
"api_key": "<chave de api>", 
"bank_code": "237", 
"conta": "58054", 
"conta_dv": "1", 
"document_number": "00000000000000", 
"legal_name": "API TEST BANK ACCOUNT"
}'
```
2. Altere o seu recebedor principal para utilizar a conta bancária criada:
```bash
curl -L -X PUT 'https://api.pagar.me/1/recipients/<id do recebedor default>' \
-H 'content-type: application/json' \
--data-raw '{
"api_key": "<chave de api>",
"bank_account_id": "<id da nova conta bancaria>"
}'
```
3. Logue na pilot …
> Release v0.24.1

- packages/pilot/src/containers/EmptyState/InfoCard/styles.css
Remove a linha roxa debaixo dos botões de link do emptyState.
> chore: remove underline from a tag

- packages/pilot/src/pages/Account/actions/epic.js
Removendo trava que impede clientes Link.me de acessar a dashboard.
> EXP-100 feat(login): allow payment_link_app company to login

- packages/pilot/src/containers/Header/index.js
- packages/pilot/src/containers/Sidebar/index.js
- packages/pilot/src/pages/LoggedArea/Header.js
- packages/pilot/src/pages/LoggedArea/Sidebar.js
- packages/pilot/src/pages/LoggedArea/index.js
Removendo os seguintes botões quando cliente Link.me acessar a dash:
- Logar com company do type `payment_link_app`;
- Não deverá ser mostrado no header a informação do ambiente que vc está;
- Não deverá ser mostrado no site o botão para voltar pra dash antiga.
> EXP-100 payment_link_app: removing buttons

- packages/pilot/src/containers/Settings/Company/GeneralInfoTab/index.js
- packages/pilot/src/containers/Settings/Company/index.js
- packages/pilot/src/pages/CompanySettings/index.js
Este PR oculta o card de api_key e encryption_key da pilot para os clientes com o type `payment_link_app`
> EXP-97 chore: hidden api key to customers of payment link

- packages/pilot/public/locales/pt/translations.json
Atualiza a label da coluna `Valor Total` da listagem de link de pagamentos para `Valor Pago`.
> plinks: update total_paid column label

- packages/pilot/src/pages/Account/actions/epic.js
- packages/pilot/src/vendor/zopim.js
Este pr adiciona as tags ao chat do zoopim para facilitar o atendimento do RC
as tags adicionadas foram:
- id da company
- tipo da company
- permissão do usuário
- aplicação: dashboard beta
- baixar. a branch
- subir a dashboard localmente
- efetuar login
- iniciar um atendimento do chat (combinar com o rc antes de fazer isso)
- verificar se os dados apareceram corretamente para a pessoa do rc
esse fluxo foi testando com o Italo do rc onde eu o @andrecondessa e o @Matheus-Maciel  testamos em call
> EXP-143 Add zoopim tags

- .github/CODEOWNERS
- packages/pilot/package.json
- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/containers/Sidebar/index.js
- packages/pilot/src/containers/Sidebar/style.css
- packages/pilot/src/pages/LoggedArea/routes.js
- yarn.lock
Atualmente temos o botão "Voltar para a versão 1.0" na Pilot, o texto desse botão confunde alguns usuários, que acham que ao clicar vão mudar a versão da API.
> CRED-13 Ajuste no CTA de "Voltar para a Dashboard legada"

- packages/pilot/src/pages/EmptyState/EmptyState.js
Nesse Pr ocultamos o onboarding de perguntas sobre a company para companies do link
Para testar esse PR você precisar criar um campany pelo auto-cred e pelo link.app para testar se o onboarding está sendo mostrado ou não
Para logar com as companies do link precisamos comentar a linha 97 desse arquivo
https://github.com/pagarme/pilot/blob/0000000000000000000000000000000000000000%3A/packages/pilot/src/pages/Account/actions/epic.js#L97
e adicionar um eslint-disable no começo da página
> EXP-95 chore: remove onboarding company payment-link-app

- packages/pilot/src/containers/Balance/index.js
- packages/pilot/src/containers/Header/index.js
- packages/pilot/src/containers/Settings/Company/index.js
- packages/pilot/src/containers/Sidebar/index.js
- packages/pilot/src/pages/Account/actions/epic.js
- packages/pilot/src/pages/CompanySettings/index.js
- packages/pilot/src/pages/EmptyState/EmptyState.js
- packages/pilot/src/validation/isPaymentLink.js
Precisamos padronizar a verificação de company do tipo `payment_link_app`. Esse PR refatora todos os arquivos alterados pelos PRs que checavam o tipo da company.
PRs alterados:
**Obs.:** Como todos os fluxos já foram validados anteriormente, devemos verificar apenas se nada foi alterado:
Não mostrar onboarding para companies link
Logar com uma company normal e verificar se está mostrando api_key e versionamento da api.
Logar com uma company `payment_link_app` e checar se os campos estão ocultos.
Acessar pelo [link de debug](https://www.googletagmanager.com/start_preview/gtm?uiv2&id=GTM-MMGHSNN&check_preview_status=1&gtm_auth=mtpUyy_l-sQ4X2XQvsZDRw&gtm_preview=env-5&gtm_debug=x&url=http%3A%2F%2Flocalhost%3A3000%2F) do gtm no chrome
Verificar se o painel de debug do gtm aparece na parte …
> EXP-148: Padroniza verificação do tipo de company

- packages/pilot/src/containers/Account/Presentation.js
Removendo os seguintes botões da pilot:
- Github;
- Voltar para área de teste.
Reference https://mundipagg.atlassian.net/secure/RapidBoard.jspa?rapidView=185&projectKey=EXP&modal=detail&selectedIssue=EXP-96
- Executar `env REACT_APP_API_ENVIROMENT=live yarn start`
- Acessar a página de login e não ver ambos os botões citados.
> EXP-96 fix(login): remove test back button

- packages/pilot/src/pages/Account/actions/epic.js
Hoje o erro de ambiente inválido para companies não `active` não está sendo exibido. Isto ocorre pois em um dos Observers do `companyEpic` não estamos retornando um `Observable`, assim consequentemente nenhuma ação de erro do redux é disparada. Este PR adiciona este retorno de `Observable` ao nosso epico.
1. Suba a aplicação em modo `live`:
```bash
env REACT_APP_API_ENVIRONMENT=live yarn start
```
2. Faça o login com uma company com status diferente de `active`
> EXP-145 - Corrige erro de ambiente inválido para companies não ativas

- packages/pilot/src/containers/TransactionsList/tableColumns.js
Percebemos que a versão 2017-07-17 permite transações sem customer. Hoje a dashboard atual usa como fallback nesse caso para exibição de nome o card_holder_name na listagem de transação.Implementar o comportamento semelhante para que os usuários que hoje operam dessa forma consigam usar a pilot sem problema.
Este pr implementa o comportamento semelhante para a listagem de transações da pilot
- baixar a branch add/customer-name-fallaback
- criar uma transação na versão de api 2017-07-17 sem informar os campos relacionados a customer no body
- abrir a listagem de transações rodando a pilot localmente
- o campo nome deve ter sido preenchido com o valor do card_holder_name
> EXP-173 transaction: add customer name fallback in list

- packages/cockpit/src/balance/data/index.js
- packages/pilot/src/containers/RecipientDetails/index.js
- packages/pilot/src/pages/Balance/Balance.js
- packages/pilot/src/pages/Recipients/Detail/index.js
Após testarmos a release do linkme, descobrimos que o extrato estava dando erro para novos clientes linkme.
Esse PR refatora a request de antecipação pendente para ser feita apenas por companies que não possuem antecipação compulsória.
- Crie uma company nova no linkme
- Acesse a branch `fix/balance-error`
- Rode `yarn` na pasta raiz do projeto
- Em Extrato
- Em `recipients` acesse o detalhe do recebedor
- Verifique se o erro `Method not allowed` não é mais mostrado.
> EXP-186: Corrige erro no extrato para novos clientes Link.me

- packages/pilot/src/pages/Root.js
Hoje ao logar com uma company na pilot estamos mostrando uma tela onde pedimos para o usuário escolher qual dashboard deseja usar:
Precisamos impedir o redirecionamento de clientes linkme para essa rota.
- Acesse a branch `remove/redirect`
- Entre com uma company do tipo `payment_link_app`
> Pode ser necessário comentar ou excluir a variável `recaptchaToken` daqui: https://github.com/pagarme/pilot/blob/b1803c1b9a5b3f12b319cd54103c36935650cb97/packages/pilot/src/containers/Account/LoginForm/index.js#L70
- Não deve ser mostrado a escolha de dashboard
> EXP-200: Remove redirecionamento para escolha de dashboard de companies paymentLink

- packages/cockpit/src/transactions/details/isCapturable.js
Transações criadas com encryption key tem até 5 horas para serem capturadas. Este PR corrige a validação que fazemos no cockpit quanto à isto
1. Crie uma transação recusada com encryption key e verifique se é capturável (basta gerar uma recusa em um link de pagamento)
> EXP-203 - Corrige capability de captura de transações

- packages/pilot/src/containers/Account/LoginForm/index.js
Esse PR força o recaptcha a gerar um novo token em cada requisição em /sessions.
Isto é necessário pois um token só pode ser usado para validar o recaptcha uma vez, caso seja, utilizado duas vezes o recaptcha irá dizer que é um cliente invalido.
> chore: refactor avoid recaptcha use last token

- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/containers/Header/index.js
Realiza o ajuste das traduções no botão enviroment da nova dashboard.
Também esconde para que esse botão só apareça no ambiente de live.
Essas traduções foram removidas no PR https://github.com/pagarme/pilot/pull/1697/files, estou ajustando elas novamente.
> chore: update header environmnets btn translation

- packages/cockpit/src/balance/operations/buildRequest.js
Atualmente a pilot busca por dois status simultaneamente em nossa rota `/payables`, porém, após migração ao Atlas esse tipo de filtro simultâneo deixou de funcionar por não ser documentado antes. A pilot buscava payables dos seguintes status:
- `prepaid` - Payables que estão no fluxo de alguma task serem processados
- `waiting_funds` - Payables que ainda serão processados
Como fazer duas requests para buscar ambos os status quebraria nossa paginação (por não conseguirmos garantir 15 ou mais itens por request), neste PR ajusto o extrato futuro para buscar somente payables `waiting_funds`
1. Acesse a página de extrato e clique em "A Receber", devem aparecer linhas na tabela caso tenha recebíveis disponíveis em sua conta. Note que a ordenação das linhas é feita primeiramente por `id`, …
> EXP-234 - Corrige exibição de recebíveis no Extrato

- packages/pilot/src/containers/TransactionDetails/index.js
- packages/pilot/src/pages/Transactions/Details/Details.js
Este PR adiciona o uso de permissionamento de ações de transação que já haviamos definido mas não estava em uso (??). Adiciono também a condição de que sellers de link.me não podem estornar transações.         
1. Faça o login com usuário de escrita/leitura/admin e verifique se o permissionamento está de acordo
- Companies Linkme - Somente o admin pode fazer estorno
- Demais companies - Qualquer usuário que não seja `read_only` consegue estornar, reprocessar e capturar transações
> EXP-271 - Detalhes de transação - Adiciona permissionamento de ações

- packages/cockpit/src/balance/operations/operations.js
- packages/cockpit/src/balance/operations/operations.test.js
- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/components/Operations/operationsTableColumns.js
- packages/pilot/src/components/SidebarSummary/index.js
- packages/pilot/src/components/SidebarSummary/style.css
- packages/pilot/src/containers/Header/index.js
- packages/pilot/src/containers/Settings/Company/TeamInfoTab/TeamManagement/AddNewUserModal.js
- packages/pilot/src/containers/Settings/Company/TeamInfoTab/TeamManagement/UserTable.js
- packages/pilot/src/containers/Settings/Company/TeamInfoTab/TeamManagement/index.js
- packages/pilot/src/containers/Settings/Company/TeamInfoTab/index.js
- packages/pilot/src/containers/Settings/Company/index.js
- packages/pilot/src/containers/Sidebar/Sections.js
- packages/pilot/src/containers/Sidebar/index.js
- packages/pilot/src/containers/TransactionDetails/index.js
- packages/pilot/src/pages/LoggedArea/Header.js
- packages/pilot/src/pages/LoggedArea/Sidebar.js
- packages/pilot/src/pages/LoggedArea/Sidebar.test.js
- packages/pilot/src/pages/LoggedArea/__snapshots__/Sidebar.test.js.snap
- packages/pilot/src/pages/LoggedArea/index.js
- packages/pilot/src/pages/LoggedArea/routes.js
- packages/pilot/src/pages/LoggedArea/routes.test.js
- packages/pilot/src/pages/Transactions/Details/Details.js
- packages/pilot/src/utils/helpers/getPermission.js
- packages/pilot/src/validation/isLinkmeSeller.js
Esta Release consiste das limitações de acesso necessárias para usuários seller de link.me (read_only e read_write). Este tipo de usuário não deve ser capaz de visualizar dados sensíveis da conta como o saldo disponível para saque, e também não deve ser capaz de realizar saques. Usuários seller tem acesso somente às telas de gerenciamento de links de pagamento e de transações.
- Testar roteamento de usuários de acordo com sua permissão
- Usuários seller (read_write/read_only) devem ter acesso somente à
- Transações
- Links de pagamento
- Configurações de usuário
- Usuários admin não devem ter acesso às telas de Recebedores
- Usuários Seller não devem ser capazes de realizar saque e visualizar o saldo disponível
- Companies Link.me agora possuem acesso à aba de equipes na tela de …
> Release - Perfil de vendedor

- packages/pilot/src/pages/PaymentLinks/List/List.js
Esconder botão de "Criar Link de Pagamentos" para clientes com permissão read_only
Entrar com um usuário com permissão read_only na tela de listagem de links de pagamento e verificar se o card que contém o botão para criação de novos links está escondido.
[CRED-230](https://mundipagg.atlassian.net/browse/CRED-230)
> fix: hide create payment link for read_only users

- packages/pilot/src/pages/Account/actions/reducer.js
- packages/pilot/src/pages/Account/actions/reducer.test.js
Em sandbox não é possível visualizar as taxas atreladas a company, o que confundia alguns clientes. Foi verificado que as taxas sempre vão ser referentes a **live** independente do ambiente. Dessa forma, foi alterado o caminho de leitura da mesma na pilot.
> settings: update test fees

- packages/pilot/src/pages/Account/actions/epic.js
adicionar as seguintes novas tags ao chat da pilot
1- E-mail que está logado
2- Status da company
3- Versão da API (só live)
4- Saldo bloqueado (live)
- Rodar o projeto;
- Abrir a aba de network;
- Logar com uma conta e verificar a request feito que obtém os dados da company. Verificar se os campos colocados no código batem com o payload de resposta da API.
> EXP-269 feat(zopim): add more user and company tags

- packages/pilot/package.json
- packages/pilot/src/components/FeesDetails/__snapshots__/FeeDetails.test.js.snap
- packages/pilot/src/components/FeesDetails/index.js
- packages/pilot/src/pages/Account/actions/actions.js
- packages/pilot/src/pages/Account/actions/epic.js
- packages/pilot/src/pages/Account/actions/reducer.js
- packages/pilot/src/pages/Account/actions/reducer.test.js
- packages/pilot/src/pages/CompanySettings/index.js
- packages/pilot/src/pages/EmptyState/EmptyState.js
- packages/pilot/stories/containers/Onboarding/index.js
- packages/pilot/stories/containers/Onboarding/mocks.js
- yarn.lock
As taxas de MDR dos clientes atualmente estão cadastradas em dois locais: dentro da company e na tabela feePreset. Foi pedido para alterarmos a forma como cadastramos os clientes com antecipação compulsoria na plataforma para, ao inves de buscar cadastrar as taxas nas companies, realizarmos os cadastro na tabela feePreset.
Entretanto, as taxas ainda existirão dentro da company e serão utilizadas como um fallback. Se houver taxas no feePreset, serão usadas as taxas do feePreset, caso não exista feePreset configurado para o recebedor, serão usadas as taxas da company.
Desta forma, este PR altera a busca das taxas que são aplicadas no cliente, priorizando primeiro a informação do feePreset, e, caso não exista, usando a informação da company.
> CRED-225 Buscar as taxas no FeePreset

- packages/pilot/src/pages/Anticipation/Anticipation.js
Na tela de criar a antecipação dos clientes, o valor a ser antecipado está sendo montado com base na resposta do endponit  [`POST /recipient/:recipientId/bulk_anticipation`](https://docs.pagar.me/reference#criando-uma-antecipa%C3%A7%C3%A3o).
Atualmente está sendo utilizado a soma das propriedades `anticipation_fee` e `fee` para exibir o custo da antecipação do cliente. Entretanto, o `fee` se refere ao MDR e nao ao custo de antecipacao, e isto [acaba confundindo os clientes](https://pagarme.slack.com/archives/C3LUBHK5J/p1599057539050700) principalmente por diferir do comportamento da dashboard antiga.
> Corrigi o calculo de antecipação

- packages/pilot/src/pages/Account/actions/epic.js
Exigindo que clientes com a capability `allow_dashboard_login` possam fazer login na pilot.
*OBS*: Foi verificado com o @augusto-jm-amaral que todas as company_templates do stone_mais(mei) estão com a capability como `false`.
> EXP-204 feat(Login): update can access login rule

- packages/pilot/public/locales/pt/translations.json
- packages/pilot/src/containers/PaymentLinks/List/PaymentLinkAdd/FirstStep/validators.js
- packages/pilot/src/formatters/paymentLinkSpec.js
Este PR seta o campo de tempo de expiração do link de pagamento como opcional. Desta forma, criando links com prazo indeterminado.
> CRED-291 - plinks: update set expiration_in as optional

- packages/pilot/src/containers/Header/index.js
Exibe a opção de acessar a dashboard legada para clientes que não sejam payment_link.
> chore: add legacy dashboard option

- packages/pilot/src/containers/RecipientTable/statusLegend.js
Quando a company possui um recebedor com um status inválido não é possível abrir a aba de recebedores.
> chore: validate recipient status
